packages:
    - 'apps/*'
    - 'convex'
    - 'packages/*'

allowBuilds:
    '@tsparticles/engine': false
    esbuild: true
    lightningcss: true
    unrs-resolver: true

overrides:
    js-yaml: 4.3.0
    postcss: 8.5.23

minimumReleaseAgeExclude:
    - '@fluxerjs/builders@2.1.0'
    - '@fluxerjs/collection@2.1.0'
    - '@fluxerjs/core@2.1.0'
    - '@fluxerjs/rest@2.1.0'
    - '@fluxerjs/types@2.1.0'
    - '@fluxerjs/util@2.1.0'
    - '@fluxerjs/ws@2.1.0'
