packages:
    - 'apps/*'
    - 'convex'
    - 'packages/*'

allowBuilds:
    '@tsparticles/engine': false
    esbuild: true
    lightningcss: true
    unrs-resolver: true

patchedDependencies:
    '@fluxerjs/core@2.0.1': patches/@fluxerjs__core@2.0.1.patch
    '@fluxerjs/rest@2.0.1': patches/@fluxerjs__rest@2.0.1.patch
