/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileBuilderRouteImport } from './routes/profile-builder'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DocsTopicRouteImport } from './routes/docs/topic'
import { Route as DashboardGuildIdRouteImport } from './routes/dashboard.$guildId'
import { Route as DocsTopicIndexRouteImport } from './routes/docs/topic/index'
import { Route as DashboardGuildIdIndexRouteImport } from './routes/dashboard/$guildId/index'
import { Route as DocsTopicSplatRouteImport } from './routes/docs/topic/$'
import { Route as DocsApiSearchRouteImport } from './routes/docs/api/search'
import { Route as DashboardGuildIdStructureRouteImport } from './routes/dashboard/$guildId/structure'
import { Route as DashboardGuildIdModerationRouteImport } from './routes/dashboard/$guildId/moderation'
import { Route as DashboardGuildIdMessagingRouteImport } from './routes/dashboard/$guildId/messaging'
import { Route as DashboardGuildIdLoggingRouteImport } from './routes/dashboard/$guildId/logging'
import { Route as DashboardGuildIdInvitesRouteImport } from './routes/dashboard/$guildId/invites'
import { Route as DashboardGuildIdGeneralRouteImport } from './routes/dashboard/$guildId/general'
import { Route as DashboardGuildIdEventsRouteImport } from './routes/dashboard.$guildId.events'
import { Route as DashboardGuildIdCommunityRouteImport } from './routes/dashboard/$guildId/community'
import { Route as DashboardGuildIdAuditRouteImport } from './routes/dashboard/$guildId/audit'
import { Route as DashboardGuildIdAccessRouteImport } from './routes/dashboard/$guildId/access'
import { Route as AuthFluxerLoginRouteImport } from './routes/auth/fluxer/login'
import { Route as AuthFluxerCallbackRouteImport } from './routes/auth/fluxer/callback'
import { Route as DashboardGuildIdCommunityIndexRouteImport } from './routes/dashboard/$guildId/community/index'
import { Route as DashboardGuildIdAccessIndexRouteImport } from './routes/dashboard/$guildId/access/index'
import { Route as DashboardGuildIdCommunityXpRouteImport } from './routes/dashboard/$guildId/community/xp'
import { Route as DashboardGuildIdCommunityVcGeneratorRouteImport } from './routes/dashboard/$guildId/community/vc-generator'
import { Route as DashboardGuildIdCommunityTicketsRouteImport } from './routes/dashboard/$guildId/community/tickets'
import { Route as DashboardGuildIdCommunitySuggestionsRouteImport } from './routes/dashboard/$guildId/community/suggestions'
import { Route as DashboardGuildIdCommunityProfileBuilderRouteImport } from './routes/dashboard/$guildId/community/profile-builder'
import { Route as DashboardGuildIdCommunityGiveawaysRouteImport } from './routes/dashboard/$guildId/community/giveaways'
import { Route as DashboardGuildIdAccessVerificationRouteImport } from './routes/dashboard/$guildId/access/verification'
import { Route as DashboardGuildIdAccessRoleReconciliationRouteImport } from './routes/dashboard/$guildId/access/role-reconciliation'
import { Route as DashboardGuildIdAccessReactionRolesRouteImport } from './routes/dashboard/$guildId/access/reaction-roles'
import { Route as DashboardGuildIdAccessCommandAccessRouteImport } from './routes/dashboard/$guildId/access/command-access'
import { Route as DashboardGuildIdAccessAutorolesRouteImport } from './routes/dashboard/$guildId/access/autoroles'

const ProfileBuilderRoute = ProfileBuilderRouteImport.update({
  id: '/profile-builder',
  path: '/profile-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DocsTopicRoute = DocsTopicRouteImport.update({
  id: '/topic',
  path: '/topic',
  getParentRoute: () => DocsRoute,
} as any)
const DashboardGuildIdRoute = DashboardGuildIdRouteImport.update({
  id: '/$guildId',
  path: '/$guildId',
  getParentRoute: () => DashboardRoute,
} as any)
const DocsTopicIndexRoute = DocsTopicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsTopicRoute,
} as any)
const DashboardGuildIdIndexRoute = DashboardGuildIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardGuildIdRoute,
} as any)
const DocsTopicSplatRoute = DocsTopicSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DocsTopicRoute,
} as any)
const DocsApiSearchRoute = DocsApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => DocsRoute,
} as any)
const DashboardGuildIdStructureRoute =
  DashboardGuildIdStructureRouteImport.update({
    id: '/structure',
    path: '/structure',
    getParentRoute: () => DashboardGuildIdRoute,
  } as any)
const DashboardGuildIdModerationRoute =
  DashboardGuildIdModerationRouteImport.update({
    id: '/moderation',
    path: '/moderation',
    getParentRoute: () => DashboardGuildIdRoute,
  } as any)
const DashboardGuildIdMessagingRoute =
  DashboardGuildIdMessagingRouteImport.update({
    id: '/messaging',
    path: '/messaging',
    getParentRoute: () => DashboardGuildIdRoute,
  } as any)
const DashboardGuildIdLoggingRoute = DashboardGuildIdLoggingRouteImport.update({
  id: '/logging',
  path: '/logging',
  getParentRoute: () => DashboardGuildIdRoute,
} as any)
const DashboardGuildIdInvitesRoute = DashboardGuildIdInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => DashboardGuildIdRoute,
} as any)
const DashboardGuildIdGeneralRoute = DashboardGuildIdGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => DashboardGuildIdRoute,
} as any)
const DashboardGuildIdEventsRoute = DashboardGuildIdEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => DashboardGuildIdRoute,
} as any)
const DashboardGuildIdCommunityRoute =
  DashboardGuildIdCommunityRouteImport.update({
    id: '/community',
    path: '/community',
    getParentRoute: () => DashboardGuildIdRoute,
  } as any)
const DashboardGuildIdAuditRoute = DashboardGuildIdAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => DashboardGuildIdRoute,
} as any)
const DashboardGuildIdAccessRoute = DashboardGuildIdAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => DashboardGuildIdRoute,
} as any)
const AuthFluxerLoginRoute = AuthFluxerLoginRouteImport.update({
  id: '/auth/fluxer/login',
  path: '/auth/fluxer/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthFluxerCallbackRoute = AuthFluxerCallbackRouteImport.update({
  id: '/auth/fluxer/callback',
  path: '/auth/fluxer/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardGuildIdCommunityIndexRoute =
  DashboardGuildIdCommunityIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardGuildIdCommunityRoute,
  } as any)
const DashboardGuildIdAccessIndexRoute =
  DashboardGuildIdAccessIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardGuildIdAccessRoute,
  } as any)
const DashboardGuildIdCommunityXpRoute =
  DashboardGuildIdCommunityXpRouteImport.update({
    id: '/xp',
    path: '/xp',
    getParentRoute: () => DashboardGuildIdCommunityRoute,
  } as any)
const DashboardGuildIdCommunityVcGeneratorRoute =
  DashboardGuildIdCommunityVcGeneratorRouteImport.update({
    id: '/vc-generator',
    path: '/vc-generator',
    getParentRoute: () => DashboardGuildIdCommunityRoute,
  } as any)
const DashboardGuildIdCommunityTicketsRoute =
  DashboardGuildIdCommunityTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => DashboardGuildIdCommunityRoute,
  } as any)
const DashboardGuildIdCommunitySuggestionsRoute =
  DashboardGuildIdCommunitySuggestionsRouteImport.update({
    id: '/suggestions',
    path: '/suggestions',
    getParentRoute: () => DashboardGuildIdCommunityRoute,
  } as any)
const DashboardGuildIdCommunityProfileBuilderRoute =
  DashboardGuildIdCommunityProfileBuilderRouteImport.update({
    id: '/profile-builder',
    path: '/profile-builder',
    getParentRoute: () => DashboardGuildIdCommunityRoute,
  } as any)
const DashboardGuildIdCommunityGiveawaysRoute =
  DashboardGuildIdCommunityGiveawaysRouteImport.update({
    id: '/giveaways',
    path: '/giveaways',
    getParentRoute: () => DashboardGuildIdCommunityRoute,
  } as any)
const DashboardGuildIdAccessVerificationRoute =
  DashboardGuildIdAccessVerificationRouteImport.update({
    id: '/verification',
    path: '/verification',
    getParentRoute: () => DashboardGuildIdAccessRoute,
  } as any)
const DashboardGuildIdAccessRoleReconciliationRoute =
  DashboardGuildIdAccessRoleReconciliationRouteImport.update({
    id: '/role-reconciliation',
    path: '/role-reconciliation',
    getParentRoute: () => DashboardGuildIdAccessRoute,
  } as any)
const DashboardGuildIdAccessReactionRolesRoute =
  DashboardGuildIdAccessReactionRolesRouteImport.update({
    id: '/reaction-roles',
    path: '/reaction-roles',
    getParentRoute: () => DashboardGuildIdAccessRoute,
  } as any)
const DashboardGuildIdAccessCommandAccessRoute =
  DashboardGuildIdAccessCommandAccessRouteImport.update({
    id: '/command-access',
    path: '/command-access',
    getParentRoute: () => DashboardGuildIdAccessRoute,
  } as any)
const DashboardGuildIdAccessAutorolesRoute =
  DashboardGuildIdAccessAutorolesRouteImport.update({
    id: '/autoroles',
    path: '/autoroles',
    getParentRoute: () => DashboardGuildIdAccessRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/profile-builder': typeof ProfileBuilderRoute
  '/dashboard/$guildId': typeof DashboardGuildIdRouteWithChildren
  '/docs/topic': typeof DocsTopicRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/auth/fluxer/callback': typeof AuthFluxerCallbackRoute
  '/auth/fluxer/login': typeof AuthFluxerLoginRoute
  '/dashboard/$guildId/access': typeof DashboardGuildIdAccessRouteWithChildren
  '/dashboard/$guildId/audit': typeof DashboardGuildIdAuditRoute
  '/dashboard/$guildId/community': typeof DashboardGuildIdCommunityRouteWithChildren
  '/dashboard/$guildId/events': typeof DashboardGuildIdEventsRoute
  '/dashboard/$guildId/general': typeof DashboardGuildIdGeneralRoute
  '/dashboard/$guildId/invites': typeof DashboardGuildIdInvitesRoute
  '/dashboard/$guildId/logging': typeof DashboardGuildIdLoggingRoute
  '/dashboard/$guildId/messaging': typeof DashboardGuildIdMessagingRoute
  '/dashboard/$guildId/moderation': typeof DashboardGuildIdModerationRoute
  '/dashboard/$guildId/structure': typeof DashboardGuildIdStructureRoute
  '/docs/api/search': typeof DocsApiSearchRoute
  '/docs/topic/$': typeof DocsTopicSplatRoute
  '/dashboard/$guildId/': typeof DashboardGuildIdIndexRoute
  '/docs/topic/': typeof DocsTopicIndexRoute
  '/dashboard/$guildId/access/autoroles': typeof DashboardGuildIdAccessAutorolesRoute
  '/dashboard/$guildId/access/command-access': typeof DashboardGuildIdAccessCommandAccessRoute
  '/dashboard/$guildId/access/reaction-roles': typeof DashboardGuildIdAccessReactionRolesRoute
  '/dashboard/$guildId/access/role-reconciliation': typeof DashboardGuildIdAccessRoleReconciliationRoute
  '/dashboard/$guildId/access/verification': typeof DashboardGuildIdAccessVerificationRoute
  '/dashboard/$guildId/community/giveaways': typeof DashboardGuildIdCommunityGiveawaysRoute
  '/dashboard/$guildId/community/profile-builder': typeof DashboardGuildIdCommunityProfileBuilderRoute
  '/dashboard/$guildId/community/suggestions': typeof DashboardGuildIdCommunitySuggestionsRoute
  '/dashboard/$guildId/community/tickets': typeof DashboardGuildIdCommunityTicketsRoute
  '/dashboard/$guildId/community/vc-generator': typeof DashboardGuildIdCommunityVcGeneratorRoute
  '/dashboard/$guildId/community/xp': typeof DashboardGuildIdCommunityXpRoute
  '/dashboard/$guildId/access/': typeof DashboardGuildIdAccessIndexRoute
  '/dashboard/$guildId/community/': typeof DashboardGuildIdCommunityIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile-builder': typeof ProfileBuilderRoute
  '/dashboard': typeof DashboardIndexRoute
  '/docs': typeof DocsIndexRoute
  '/auth/fluxer/callback': typeof AuthFluxerCallbackRoute
  '/auth/fluxer/login': typeof AuthFluxerLoginRoute
  '/dashboard/$guildId/audit': typeof DashboardGuildIdAuditRoute
  '/dashboard/$guildId/events': typeof DashboardGuildIdEventsRoute
  '/dashboard/$guildId/general': typeof DashboardGuildIdGeneralRoute
  '/dashboard/$guildId/invites': typeof DashboardGuildIdInvitesRoute
  '/dashboard/$guildId/logging': typeof DashboardGuildIdLoggingRoute
  '/dashboard/$guildId/messaging': typeof DashboardGuildIdMessagingRoute
  '/dashboard/$guildId/moderation': typeof DashboardGuildIdModerationRoute
  '/dashboard/$guildId/structure': typeof DashboardGuildIdStructureRoute
  '/docs/api/search': typeof DocsApiSearchRoute
  '/docs/topic/$': typeof DocsTopicSplatRoute
  '/dashboard/$guildId': typeof DashboardGuildIdIndexRoute
  '/docs/topic': typeof DocsTopicIndexRoute
  '/dashboard/$guildId/access/autoroles': typeof DashboardGuildIdAccessAutorolesRoute
  '/dashboard/$guildId/access/command-access': typeof DashboardGuildIdAccessCommandAccessRoute
  '/dashboard/$guildId/access/reaction-roles': typeof DashboardGuildIdAccessReactionRolesRoute
  '/dashboard/$guildId/access/role-reconciliation': typeof DashboardGuildIdAccessRoleReconciliationRoute
  '/dashboard/$guildId/access/verification': typeof DashboardGuildIdAccessVerificationRoute
  '/dashboard/$guildId/community/giveaways': typeof DashboardGuildIdCommunityGiveawaysRoute
  '/dashboard/$guildId/community/profile-builder': typeof DashboardGuildIdCommunityProfileBuilderRoute
  '/dashboard/$guildId/community/suggestions': typeof DashboardGuildIdCommunitySuggestionsRoute
  '/dashboard/$guildId/community/tickets': typeof DashboardGuildIdCommunityTicketsRoute
  '/dashboard/$guildId/community/vc-generator': typeof DashboardGuildIdCommunityVcGeneratorRoute
  '/dashboard/$guildId/community/xp': typeof DashboardGuildIdCommunityXpRoute
  '/dashboard/$guildId/access': typeof DashboardGuildIdAccessIndexRoute
  '/dashboard/$guildId/community': typeof DashboardGuildIdCommunityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/profile-builder': typeof ProfileBuilderRoute
  '/dashboard/$guildId': typeof DashboardGuildIdRouteWithChildren
  '/docs/topic': typeof DocsTopicRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/auth/fluxer/callback': typeof AuthFluxerCallbackRoute
  '/auth/fluxer/login': typeof AuthFluxerLoginRoute
  '/dashboard/$guildId/access': typeof DashboardGuildIdAccessRouteWithChildren
  '/dashboard/$guildId/audit': typeof DashboardGuildIdAuditRoute
  '/dashboard/$guildId/community': typeof DashboardGuildIdCommunityRouteWithChildren
  '/dashboard/$guildId/events': typeof DashboardGuildIdEventsRoute
  '/dashboard/$guildId/general': typeof DashboardGuildIdGeneralRoute
  '/dashboard/$guildId/invites': typeof DashboardGuildIdInvitesRoute
  '/dashboard/$guildId/logging': typeof DashboardGuildIdLoggingRoute
  '/dashboard/$guildId/messaging': typeof DashboardGuildIdMessagingRoute
  '/dashboard/$guildId/moderation': typeof DashboardGuildIdModerationRoute
  '/dashboard/$guildId/structure': typeof DashboardGuildIdStructureRoute
  '/docs/api/search': typeof DocsApiSearchRoute
  '/docs/topic/$': typeof DocsTopicSplatRoute
  '/dashboard/$guildId/': typeof DashboardGuildIdIndexRoute
  '/docs/topic/': typeof DocsTopicIndexRoute
  '/dashboard/$guildId/access/autoroles': typeof DashboardGuildIdAccessAutorolesRoute
  '/dashboard/$guildId/access/command-access': typeof DashboardGuildIdAccessCommandAccessRoute
  '/dashboard/$guildId/access/reaction-roles': typeof DashboardGuildIdAccessReactionRolesRoute
  '/dashboard/$guildId/access/role-reconciliation': typeof DashboardGuildIdAccessRoleReconciliationRoute
  '/dashboard/$guildId/access/verification': typeof DashboardGuildIdAccessVerificationRoute
  '/dashboard/$guildId/community/giveaways': typeof DashboardGuildIdCommunityGiveawaysRoute
  '/dashboard/$guildId/community/profile-builder': typeof DashboardGuildIdCommunityProfileBuilderRoute
  '/dashboard/$guildId/community/suggestions': typeof DashboardGuildIdCommunitySuggestionsRoute
  '/dashboard/$guildId/community/tickets': typeof DashboardGuildIdCommunityTicketsRoute
  '/dashboard/$guildId/community/vc-generator': typeof DashboardGuildIdCommunityVcGeneratorRoute
  '/dashboard/$guildId/community/xp': typeof DashboardGuildIdCommunityXpRoute
  '/dashboard/$guildId/access/': typeof DashboardGuildIdAccessIndexRoute
  '/dashboard/$guildId/community/': typeof DashboardGuildIdCommunityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/docs'
    | '/profile-builder'
    | '/dashboard/$guildId'
    | '/docs/topic'
    | '/dashboard/'
    | '/docs/'
    | '/auth/fluxer/callback'
    | '/auth/fluxer/login'
    | '/dashboard/$guildId/access'
    | '/dashboard/$guildId/audit'
    | '/dashboard/$guildId/community'
    | '/dashboard/$guildId/events'
    | '/dashboard/$guildId/general'
    | '/dashboard/$guildId/invites'
    | '/dashboard/$guildId/logging'
    | '/dashboard/$guildId/messaging'
    | '/dashboard/$guildId/moderation'
    | '/dashboard/$guildId/structure'
    | '/docs/api/search'
    | '/docs/topic/$'
    | '/dashboard/$guildId/'
    | '/docs/topic/'
    | '/dashboard/$guildId/access/autoroles'
    | '/dashboard/$guildId/access/command-access'
    | '/dashboard/$guildId/access/reaction-roles'
    | '/dashboard/$guildId/access/role-reconciliation'
    | '/dashboard/$guildId/access/verification'
    | '/dashboard/$guildId/community/giveaways'
    | '/dashboard/$guildId/community/profile-builder'
    | '/dashboard/$guildId/community/suggestions'
    | '/dashboard/$guildId/community/tickets'
    | '/dashboard/$guildId/community/vc-generator'
    | '/dashboard/$guildId/community/xp'
    | '/dashboard/$guildId/access/'
    | '/dashboard/$guildId/community/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile-builder'
    | '/dashboard'
    | '/docs'
    | '/auth/fluxer/callback'
    | '/auth/fluxer/login'
    | '/dashboard/$guildId/audit'
    | '/dashboard/$guildId/events'
    | '/dashboard/$guildId/general'
    | '/dashboard/$guildId/invites'
    | '/dashboard/$guildId/logging'
    | '/dashboard/$guildId/messaging'
    | '/dashboard/$guildId/moderation'
    | '/dashboard/$guildId/structure'
    | '/docs/api/search'
    | '/docs/topic/$'
    | '/dashboard/$guildId'
    | '/docs/topic'
    | '/dashboard/$guildId/access/autoroles'
    | '/dashboard/$guildId/access/command-access'
    | '/dashboard/$guildId/access/reaction-roles'
    | '/dashboard/$guildId/access/role-reconciliation'
    | '/dashboard/$guildId/access/verification'
    | '/dashboard/$guildId/community/giveaways'
    | '/dashboard/$guildId/community/profile-builder'
    | '/dashboard/$guildId/community/suggestions'
    | '/dashboard/$guildId/community/tickets'
    | '/dashboard/$guildId/community/vc-generator'
    | '/dashboard/$guildId/community/xp'
    | '/dashboard/$guildId/access'
    | '/dashboard/$guildId/community'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/docs'
    | '/profile-builder'
    | '/dashboard/$guildId'
    | '/docs/topic'
    | '/dashboard/'
    | '/docs/'
    | '/auth/fluxer/callback'
    | '/auth/fluxer/login'
    | '/dashboard/$guildId/access'
    | '/dashboard/$guildId/audit'
    | '/dashboard/$guildId/community'
    | '/dashboard/$guildId/events'
    | '/dashboard/$guildId/general'
    | '/dashboard/$guildId/invites'
    | '/dashboard/$guildId/logging'
    | '/dashboard/$guildId/messaging'
    | '/dashboard/$guildId/moderation'
    | '/dashboard/$guildId/structure'
    | '/docs/api/search'
    | '/docs/topic/$'
    | '/dashboard/$guildId/'
    | '/docs/topic/'
    | '/dashboard/$guildId/access/autoroles'
    | '/dashboard/$guildId/access/command-access'
    | '/dashboard/$guildId/access/reaction-roles'
    | '/dashboard/$guildId/access/role-reconciliation'
    | '/dashboard/$guildId/access/verification'
    | '/dashboard/$guildId/community/giveaways'
    | '/dashboard/$guildId/community/profile-builder'
    | '/dashboard/$guildId/community/suggestions'
    | '/dashboard/$guildId/community/tickets'
    | '/dashboard/$guildId/community/vc-generator'
    | '/dashboard/$guildId/community/xp'
    | '/dashboard/$guildId/access/'
    | '/dashboard/$guildId/community/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
  ProfileBuilderRoute: typeof ProfileBuilderRoute
  AuthFluxerCallbackRoute: typeof AuthFluxerCallbackRoute
  AuthFluxerLoginRoute: typeof AuthFluxerLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile-builder': {
      id: '/profile-builder'
      path: '/profile-builder'
      fullPath: '/profile-builder'
      preLoaderRoute: typeof ProfileBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/docs/topic': {
      id: '/docs/topic'
      path: '/topic'
      fullPath: '/docs/topic'
      preLoaderRoute: typeof DocsTopicRouteImport
      parentRoute: typeof DocsRoute
    }
    '/dashboard/$guildId': {
      id: '/dashboard/$guildId'
      path: '/$guildId'
      fullPath: '/dashboard/$guildId'
      preLoaderRoute: typeof DashboardGuildIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/docs/topic/': {
      id: '/docs/topic/'
      path: '/'
      fullPath: '/docs/topic/'
      preLoaderRoute: typeof DocsTopicIndexRouteImport
      parentRoute: typeof DocsTopicRoute
    }
    '/dashboard/$guildId/': {
      id: '/dashboard/$guildId/'
      path: '/'
      fullPath: '/dashboard/$guildId/'
      preLoaderRoute: typeof DashboardGuildIdIndexRouteImport
      parentRoute: typeof DashboardGuildIdRoute
    }
    '/docs/topic/$': {
      id: '/docs/topic/$'
      path: '/$'
      fullPath: '/docs/topic/$'
      preLoaderRoute: typeof DocsTopicSplatRouteImport
      parentRoute: typeof DocsTopicRoute
    }
    '/docs/api/search': {
      id: '/docs/api/search'
      path: '/api/search'
      fullPath: '/docs/api/search'
      preLoaderRoute: typeof DocsApiSearchRouteImport
      parentRoute: typeof DocsRoute
    }
    '/dashboard/$guildId/structure': {
      id: '/dashboard/$guildId/structure'
      path: '/structure'
      fullPath: '/dashboard/$guildId/structure'
      preLoaderRoute: typeof DashboardGuildIdStructureRouteImport
      parentRoute: typeof DashboardGuildIdRoute
    }
    '/dashboard/$guildId/moderation': {
      id: '/dashboard/$guildId/moderation'
      path: '/moderation'
      fullPath: '/dashboard/$guildId/moderation'
      preLoaderRoute: typeof DashboardGuildIdModerationRouteImport
      parentRoute: typeof DashboardGuildIdRoute
    }
    '/dashboard/$guildId/messaging': {
      id: '/dashboard/$guildId/messaging'
      path: '/messaging'
      fullPath: '/dashboard/$guildId/messaging'
      preLoaderRoute: typeof DashboardGuildIdMessagingRouteImport
      parentRoute: typeof DashboardGuildIdRoute
    }
    '/dashboard/$guildId/logging': {
      id: '/dashboard/$guildId/logging'
      path: '/logging'
      fullPath: '/dashboard/$guildId/logging'
      preLoaderRoute: typeof DashboardGuildIdLoggingRouteImport
      parentRoute: typeof DashboardGuildIdRoute
    }
    '/dashboard/$guildId/invites': {
      id: '/dashboard/$guildId/invites'
      path: '/invites'
      fullPath: '/dashboard/$guildId/invites'
      preLoaderRoute: typeof DashboardGuildIdInvitesRouteImport
      parentRoute: typeof DashboardGuildIdRoute
    }
    '/dashboard/$guildId/general': {
      id: '/dashboard/$guildId/general'
      path: '/general'
      fullPath: '/dashboard/$guildId/general'
      preLoaderRoute: typeof DashboardGuildIdGeneralRouteImport
      parentRoute: typeof DashboardGuildIdRoute
    }
    '/dashboard/$guildId/events': {
      id: '/dashboard/$guildId/events'
      path: '/events'
      fullPath: '/dashboard/$guildId/events'
      preLoaderRoute: typeof DashboardGuildIdEventsRouteImport
      parentRoute: typeof DashboardGuildIdRoute
    }
    '/dashboard/$guildId/community': {
      id: '/dashboard/$guildId/community'
      path: '/community'
      fullPath: '/dashboard/$guildId/community'
      preLoaderRoute: typeof DashboardGuildIdCommunityRouteImport
      parentRoute: typeof DashboardGuildIdRoute
    }
    '/dashboard/$guildId/audit': {
      id: '/dashboard/$guildId/audit'
      path: '/audit'
      fullPath: '/dashboard/$guildId/audit'
      preLoaderRoute: typeof DashboardGuildIdAuditRouteImport
      parentRoute: typeof DashboardGuildIdRoute
    }
    '/dashboard/$guildId/access': {
      id: '/dashboard/$guildId/access'
      path: '/access'
      fullPath: '/dashboard/$guildId/access'
      preLoaderRoute: typeof DashboardGuildIdAccessRouteImport
      parentRoute: typeof DashboardGuildIdRoute
    }
    '/auth/fluxer/login': {
      id: '/auth/fluxer/login'
      path: '/auth/fluxer/login'
      fullPath: '/auth/fluxer/login'
      preLoaderRoute: typeof AuthFluxerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/fluxer/callback': {
      id: '/auth/fluxer/callback'
      path: '/auth/fluxer/callback'
      fullPath: '/auth/fluxer/callback'
      preLoaderRoute: typeof AuthFluxerCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$guildId/community/': {
      id: '/dashboard/$guildId/community/'
      path: '/'
      fullPath: '/dashboard/$guildId/community/'
      preLoaderRoute: typeof DashboardGuildIdCommunityIndexRouteImport
      parentRoute: typeof DashboardGuildIdCommunityRoute
    }
    '/dashboard/$guildId/access/': {
      id: '/dashboard/$guildId/access/'
      path: '/'
      fullPath: '/dashboard/$guildId/access/'
      preLoaderRoute: typeof DashboardGuildIdAccessIndexRouteImport
      parentRoute: typeof DashboardGuildIdAccessRoute
    }
    '/dashboard/$guildId/community/xp': {
      id: '/dashboard/$guildId/community/xp'
      path: '/xp'
      fullPath: '/dashboard/$guildId/community/xp'
      preLoaderRoute: typeof DashboardGuildIdCommunityXpRouteImport
      parentRoute: typeof DashboardGuildIdCommunityRoute
    }
    '/dashboard/$guildId/community/vc-generator': {
      id: '/dashboard/$guildId/community/vc-generator'
      path: '/vc-generator'
      fullPath: '/dashboard/$guildId/community/vc-generator'
      preLoaderRoute: typeof DashboardGuildIdCommunityVcGeneratorRouteImport
      parentRoute: typeof DashboardGuildIdCommunityRoute
    }
    '/dashboard/$guildId/community/tickets': {
      id: '/dashboard/$guildId/community/tickets'
      path: '/tickets'
      fullPath: '/dashboard/$guildId/community/tickets'
      preLoaderRoute: typeof DashboardGuildIdCommunityTicketsRouteImport
      parentRoute: typeof DashboardGuildIdCommunityRoute
    }
    '/dashboard/$guildId/community/suggestions': {
      id: '/dashboard/$guildId/community/suggestions'
      path: '/suggestions'
      fullPath: '/dashboard/$guildId/community/suggestions'
      preLoaderRoute: typeof DashboardGuildIdCommunitySuggestionsRouteImport
      parentRoute: typeof DashboardGuildIdCommunityRoute
    }
    '/dashboard/$guildId/community/profile-builder': {
      id: '/dashboard/$guildId/community/profile-builder'
      path: '/profile-builder'
      fullPath: '/dashboard/$guildId/community/profile-builder'
      preLoaderRoute: typeof DashboardGuildIdCommunityProfileBuilderRouteImport
      parentRoute: typeof DashboardGuildIdCommunityRoute
    }
    '/dashboard/$guildId/community/giveaways': {
      id: '/dashboard/$guildId/community/giveaways'
      path: '/giveaways'
      fullPath: '/dashboard/$guildId/community/giveaways'
      preLoaderRoute: typeof DashboardGuildIdCommunityGiveawaysRouteImport
      parentRoute: typeof DashboardGuildIdCommunityRoute
    }
    '/dashboard/$guildId/access/verification': {
      id: '/dashboard/$guildId/access/verification'
      path: '/verification'
      fullPath: '/dashboard/$guildId/access/verification'
      preLoaderRoute: typeof DashboardGuildIdAccessVerificationRouteImport
      parentRoute: typeof DashboardGuildIdAccessRoute
    }
    '/dashboard/$guildId/access/role-reconciliation': {
      id: '/dashboard/$guildId/access/role-reconciliation'
      path: '/role-reconciliation'
      fullPath: '/dashboard/$guildId/access/role-reconciliation'
      preLoaderRoute: typeof DashboardGuildIdAccessRoleReconciliationRouteImport
      parentRoute: typeof DashboardGuildIdAccessRoute
    }
    '/dashboard/$guildId/access/reaction-roles': {
      id: '/dashboard/$guildId/access/reaction-roles'
      path: '/reaction-roles'
      fullPath: '/dashboard/$guildId/access/reaction-roles'
      preLoaderRoute: typeof DashboardGuildIdAccessReactionRolesRouteImport
      parentRoute: typeof DashboardGuildIdAccessRoute
    }
    '/dashboard/$guildId/access/command-access': {
      id: '/dashboard/$guildId/access/command-access'
      path: '/command-access'
      fullPath: '/dashboard/$guildId/access/command-access'
      preLoaderRoute: typeof DashboardGuildIdAccessCommandAccessRouteImport
      parentRoute: typeof DashboardGuildIdAccessRoute
    }
    '/dashboard/$guildId/access/autoroles': {
      id: '/dashboard/$guildId/access/autoroles'
      path: '/autoroles'
      fullPath: '/dashboard/$guildId/access/autoroles'
      preLoaderRoute: typeof DashboardGuildIdAccessAutorolesRouteImport
      parentRoute: typeof DashboardGuildIdAccessRoute
    }
  }
}

interface DashboardGuildIdAccessRouteChildren {
  DashboardGuildIdAccessAutorolesRoute: typeof DashboardGuildIdAccessAutorolesRoute
  DashboardGuildIdAccessCommandAccessRoute: typeof DashboardGuildIdAccessCommandAccessRoute
  DashboardGuildIdAccessReactionRolesRoute: typeof DashboardGuildIdAccessReactionRolesRoute
  DashboardGuildIdAccessRoleReconciliationRoute: typeof DashboardGuildIdAccessRoleReconciliationRoute
  DashboardGuildIdAccessVerificationRoute: typeof DashboardGuildIdAccessVerificationRoute
  DashboardGuildIdAccessIndexRoute: typeof DashboardGuildIdAccessIndexRoute
}

const DashboardGuildIdAccessRouteChildren: DashboardGuildIdAccessRouteChildren =
  {
    DashboardGuildIdAccessAutorolesRoute: DashboardGuildIdAccessAutorolesRoute,
    DashboardGuildIdAccessCommandAccessRoute:
      DashboardGuildIdAccessCommandAccessRoute,
    DashboardGuildIdAccessReactionRolesRoute:
      DashboardGuildIdAccessReactionRolesRoute,
    DashboardGuildIdAccessRoleReconciliationRoute:
      DashboardGuildIdAccessRoleReconciliationRoute,
    DashboardGuildIdAccessVerificationRoute:
      DashboardGuildIdAccessVerificationRoute,
    DashboardGuildIdAccessIndexRoute: DashboardGuildIdAccessIndexRoute,
  }

const DashboardGuildIdAccessRouteWithChildren =
  DashboardGuildIdAccessRoute._addFileChildren(
    DashboardGuildIdAccessRouteChildren,
  )

interface DashboardGuildIdCommunityRouteChildren {
  DashboardGuildIdCommunityGiveawaysRoute: typeof DashboardGuildIdCommunityGiveawaysRoute
  DashboardGuildIdCommunityProfileBuilderRoute: typeof DashboardGuildIdCommunityProfileBuilderRoute
  DashboardGuildIdCommunitySuggestionsRoute: typeof DashboardGuildIdCommunitySuggestionsRoute
  DashboardGuildIdCommunityTicketsRoute: typeof DashboardGuildIdCommunityTicketsRoute
  DashboardGuildIdCommunityVcGeneratorRoute: typeof DashboardGuildIdCommunityVcGeneratorRoute
  DashboardGuildIdCommunityXpRoute: typeof DashboardGuildIdCommunityXpRoute
  DashboardGuildIdCommunityIndexRoute: typeof DashboardGuildIdCommunityIndexRoute
}

const DashboardGuildIdCommunityRouteChildren: DashboardGuildIdCommunityRouteChildren =
  {
    DashboardGuildIdCommunityGiveawaysRoute:
      DashboardGuildIdCommunityGiveawaysRoute,
    DashboardGuildIdCommunityProfileBuilderRoute:
      DashboardGuildIdCommunityProfileBuilderRoute,
    DashboardGuildIdCommunitySuggestionsRoute:
      DashboardGuildIdCommunitySuggestionsRoute,
    DashboardGuildIdCommunityTicketsRoute:
      DashboardGuildIdCommunityTicketsRoute,
    DashboardGuildIdCommunityVcGeneratorRoute:
      DashboardGuildIdCommunityVcGeneratorRoute,
    DashboardGuildIdCommunityXpRoute: DashboardGuildIdCommunityXpRoute,
    DashboardGuildIdCommunityIndexRoute: DashboardGuildIdCommunityIndexRoute,
  }

const DashboardGuildIdCommunityRouteWithChildren =
  DashboardGuildIdCommunityRoute._addFileChildren(
    DashboardGuildIdCommunityRouteChildren,
  )

interface DashboardGuildIdRouteChildren {
  DashboardGuildIdAccessRoute: typeof DashboardGuildIdAccessRouteWithChildren
  DashboardGuildIdAuditRoute: typeof DashboardGuildIdAuditRoute
  DashboardGuildIdCommunityRoute: typeof DashboardGuildIdCommunityRouteWithChildren
  DashboardGuildIdEventsRoute: typeof DashboardGuildIdEventsRoute
  DashboardGuildIdGeneralRoute: typeof DashboardGuildIdGeneralRoute
  DashboardGuildIdInvitesRoute: typeof DashboardGuildIdInvitesRoute
  DashboardGuildIdLoggingRoute: typeof DashboardGuildIdLoggingRoute
  DashboardGuildIdMessagingRoute: typeof DashboardGuildIdMessagingRoute
  DashboardGuildIdModerationRoute: typeof DashboardGuildIdModerationRoute
  DashboardGuildIdStructureRoute: typeof DashboardGuildIdStructureRoute
  DashboardGuildIdIndexRoute: typeof DashboardGuildIdIndexRoute
}

const DashboardGuildIdRouteChildren: DashboardGuildIdRouteChildren = {
  DashboardGuildIdAccessRoute: DashboardGuildIdAccessRouteWithChildren,
  DashboardGuildIdAuditRoute: DashboardGuildIdAuditRoute,
  DashboardGuildIdCommunityRoute: DashboardGuildIdCommunityRouteWithChildren,
  DashboardGuildIdEventsRoute: DashboardGuildIdEventsRoute,
  DashboardGuildIdGeneralRoute: DashboardGuildIdGeneralRoute,
  DashboardGuildIdInvitesRoute: DashboardGuildIdInvitesRoute,
  DashboardGuildIdLoggingRoute: DashboardGuildIdLoggingRoute,
  DashboardGuildIdMessagingRoute: DashboardGuildIdMessagingRoute,
  DashboardGuildIdModerationRoute: DashboardGuildIdModerationRoute,
  DashboardGuildIdStructureRoute: DashboardGuildIdStructureRoute,
  DashboardGuildIdIndexRoute: DashboardGuildIdIndexRoute,
}

const DashboardGuildIdRouteWithChildren =
  DashboardGuildIdRoute._addFileChildren(DashboardGuildIdRouteChildren)

interface DashboardRouteChildren {
  DashboardGuildIdRoute: typeof DashboardGuildIdRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardGuildIdRoute: DashboardGuildIdRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface DocsTopicRouteChildren {
  DocsTopicSplatRoute: typeof DocsTopicSplatRoute
  DocsTopicIndexRoute: typeof DocsTopicIndexRoute
}

const DocsTopicRouteChildren: DocsTopicRouteChildren = {
  DocsTopicSplatRoute: DocsTopicSplatRoute,
  DocsTopicIndexRoute: DocsTopicIndexRoute,
}

const DocsTopicRouteWithChildren = DocsTopicRoute._addFileChildren(
  DocsTopicRouteChildren,
)

interface DocsRouteChildren {
  DocsTopicRoute: typeof DocsTopicRouteWithChildren
  DocsIndexRoute: typeof DocsIndexRoute
  DocsApiSearchRoute: typeof DocsApiSearchRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsTopicRoute: DocsTopicRouteWithChildren,
  DocsIndexRoute: DocsIndexRoute,
  DocsApiSearchRoute: DocsApiSearchRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
  ProfileBuilderRoute: ProfileBuilderRoute,
  AuthFluxerCallbackRoute: AuthFluxerCallbackRoute,
  AuthFluxerLoginRoute: AuthFluxerLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
