/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DocsTopicRouteImport } from './routes/docs/topic'
import { Route as DashboardGuildIdRouteImport } from './routes/dashboard.$guildId'
import { Route as DotwellKnownJwksDotjsonRouteImport } from './routes/[.]well-known.jwks[.]json'
import { Route as DocsTopicIndexRouteImport } from './routes/docs/topic/index'
import { Route as DashboardGuildIdIndexRouteImport } from './routes/dashboard/$guildId/index'
import { Route as DocsTopicSplatRouteImport } from './routes/docs/topic/$'
import { Route as DocsApiSearchRouteImport } from './routes/docs/api/search'
import { Route as DashboardGuildIdStructureRouteImport } from './routes/dashboard/$guildId/structure'
import { Route as DashboardGuildIdMessagingRouteImport } from './routes/dashboard/$guildId/messaging'
import { Route as DashboardGuildIdGeneralRouteImport } from './routes/dashboard/$guildId/general'
import { Route as DashboardGuildIdEventsRouteImport } from './routes/dashboard/$guildId/events'
import { Route as DashboardGuildIdSplatRouteImport } from './routes/dashboard/$guildId/$'
import { Route as AuthFluxerLoginRouteImport } from './routes/auth/fluxer/login'
import { Route as AuthFluxerCallbackRouteImport } from './routes/auth/fluxer/callback'
import { Route as AuthConvexTokenRouteImport } from './routes/auth/convex/token'
import { Route as DashboardGuildIdStructureIndexRouteImport } from './routes/dashboard/$guildId/structure/index'
import { Route as DashboardGuildIdMessagingIndexRouteImport } from './routes/dashboard/$guildId/messaging/index'
import { Route as DashboardGuildIdGeneralIndexRouteImport } from './routes/dashboard/$guildId/general/index'
import { Route as DashboardGuildIdEventsIndexRouteImport } from './routes/dashboard/$guildId/events/index'
import { Route as DashboardGuildIdStructureRunsRouteImport } from './routes/dashboard/$guildId/structure/runs'
import { Route as DashboardGuildIdStructureDeployRouteImport } from './routes/dashboard/$guildId/structure/deploy'
import { Route as DashboardGuildIdStructureCurrentRouteImport } from './routes/dashboard/$guildId/structure/current'
import { Route as DashboardGuildIdStructureCompareRouteImport } from './routes/dashboard/$guildId/structure/compare'
import { Route as DashboardGuildIdStructureBackupsRouteImport } from './routes/dashboard/$guildId/structure/backups'
import { Route as DashboardGuildIdMessagingMessageBuilderRouteImport } from './routes/dashboard/$guildId/messaging/message-builder'
import { Route as DashboardGuildIdGeneralCommandPrefixRouteImport } from './routes/dashboard/$guildId/general/command-prefix'
import { Route as DashboardGuildIdEventsAuditEventsRouteImport } from './routes/dashboard/$guildId/events/audit-events'

const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DocsTopicRoute = DocsTopicRouteImport.update({
  id: '/topic',
  path: '/topic',
  getParentRoute: () => DocsRoute,
} as any)
const DashboardGuildIdRoute = DashboardGuildIdRouteImport.update({
  id: '/$guildId',
  path: '/$guildId',
  getParentRoute: () => DashboardRoute,
} as any)
const DotwellKnownJwksDotjsonRoute = DotwellKnownJwksDotjsonRouteImport.update({
  id: '/.well-known/jwks.json',
  path: '/.well-known/jwks.json',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsTopicIndexRoute = DocsTopicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsTopicRoute,
} as any)
const DashboardGuildIdIndexRoute = DashboardGuildIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardGuildIdRoute,
} as any)
const DocsTopicSplatRoute = DocsTopicSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DocsTopicRoute,
} as any)
const DocsApiSearchRoute = DocsApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => DocsRoute,
} as any)
const DashboardGuildIdStructureRoute =
  DashboardGuildIdStructureRouteImport.update({
    id: '/structure',
    path: '/structure',
    getParentRoute: () => DashboardGuildIdRoute,
  } as any)
const DashboardGuildIdMessagingRoute =
  DashboardGuildIdMessagingRouteImport.update({
    id: '/messaging',
    path: '/messaging',
    getParentRoute: () => DashboardGuildIdRoute,
  } as any)
const DashboardGuildIdGeneralRoute = DashboardGuildIdGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => DashboardGuildIdRoute,
} as any)
const DashboardGuildIdEventsRoute = DashboardGuildIdEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => DashboardGuildIdRoute,
} as any)
const DashboardGuildIdSplatRoute = DashboardGuildIdSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DashboardGuildIdRoute,
} as any)
const AuthFluxerLoginRoute = AuthFluxerLoginRouteImport.update({
  id: '/auth/fluxer/login',
  path: '/auth/fluxer/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthFluxerCallbackRoute = AuthFluxerCallbackRouteImport.update({
  id: '/auth/fluxer/callback',
  path: '/auth/fluxer/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConvexTokenRoute = AuthConvexTokenRouteImport.update({
  id: '/auth/convex/token',
  path: '/auth/convex/token',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardGuildIdStructureIndexRoute =
  DashboardGuildIdStructureIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardGuildIdStructureRoute,
  } as any)
const DashboardGuildIdMessagingIndexRoute =
  DashboardGuildIdMessagingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardGuildIdMessagingRoute,
  } as any)
const DashboardGuildIdGeneralIndexRoute =
  DashboardGuildIdGeneralIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardGuildIdGeneralRoute,
  } as any)
const DashboardGuildIdEventsIndexRoute =
  DashboardGuildIdEventsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardGuildIdEventsRoute,
  } as any)
const DashboardGuildIdStructureRunsRoute =
  DashboardGuildIdStructureRunsRouteImport.update({
    id: '/runs',
    path: '/runs',
    getParentRoute: () => DashboardGuildIdStructureRoute,
  } as any)
const DashboardGuildIdStructureDeployRoute =
  DashboardGuildIdStructureDeployRouteImport.update({
    id: '/deploy',
    path: '/deploy',
    getParentRoute: () => DashboardGuildIdStructureRoute,
  } as any)
const DashboardGuildIdStructureCurrentRoute =
  DashboardGuildIdStructureCurrentRouteImport.update({
    id: '/current',
    path: '/current',
    getParentRoute: () => DashboardGuildIdStructureRoute,
  } as any)
const DashboardGuildIdStructureCompareRoute =
  DashboardGuildIdStructureCompareRouteImport.update({
    id: '/compare',
    path: '/compare',
    getParentRoute: () => DashboardGuildIdStructureRoute,
  } as any)
const DashboardGuildIdStructureBackupsRoute =
  DashboardGuildIdStructureBackupsRouteImport.update({
    id: '/backups',
    path: '/backups',
    getParentRoute: () => DashboardGuildIdStructureRoute,
  } as any)
const DashboardGuildIdMessagingMessageBuilderRoute =
  DashboardGuildIdMessagingMessageBuilderRouteImport.update({
    id: '/message-builder',
    path: '/message-builder',
    getParentRoute: () => DashboardGuildIdMessagingRoute,
  } as any)
const DashboardGuildIdGeneralCommandPrefixRoute =
  DashboardGuildIdGeneralCommandPrefixRouteImport.update({
    id: '/command-prefix',
    path: '/command-prefix',
    getParentRoute: () => DashboardGuildIdGeneralRoute,
  } as any)
const DashboardGuildIdEventsAuditEventsRoute =
  DashboardGuildIdEventsAuditEventsRouteImport.update({
    id: '/audit-events',
    path: '/audit-events',
    getParentRoute: () => DashboardGuildIdEventsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/.well-known/jwks.json': typeof DotwellKnownJwksDotjsonRoute
  '/dashboard/$guildId': typeof DashboardGuildIdRouteWithChildren
  '/docs/topic': typeof DocsTopicRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/auth/convex/token': typeof AuthConvexTokenRoute
  '/auth/fluxer/callback': typeof AuthFluxerCallbackRoute
  '/auth/fluxer/login': typeof AuthFluxerLoginRoute
  '/dashboard/$guildId/$': typeof DashboardGuildIdSplatRoute
  '/dashboard/$guildId/events': typeof DashboardGuildIdEventsRouteWithChildren
  '/dashboard/$guildId/general': typeof DashboardGuildIdGeneralRouteWithChildren
  '/dashboard/$guildId/messaging': typeof DashboardGuildIdMessagingRouteWithChildren
  '/dashboard/$guildId/structure': typeof DashboardGuildIdStructureRouteWithChildren
  '/docs/api/search': typeof DocsApiSearchRoute
  '/docs/topic/$': typeof DocsTopicSplatRoute
  '/dashboard/$guildId/': typeof DashboardGuildIdIndexRoute
  '/docs/topic/': typeof DocsTopicIndexRoute
  '/dashboard/$guildId/events/audit-events': typeof DashboardGuildIdEventsAuditEventsRoute
  '/dashboard/$guildId/general/command-prefix': typeof DashboardGuildIdGeneralCommandPrefixRoute
  '/dashboard/$guildId/messaging/message-builder': typeof DashboardGuildIdMessagingMessageBuilderRoute
  '/dashboard/$guildId/structure/backups': typeof DashboardGuildIdStructureBackupsRoute
  '/dashboard/$guildId/structure/compare': typeof DashboardGuildIdStructureCompareRoute
  '/dashboard/$guildId/structure/current': typeof DashboardGuildIdStructureCurrentRoute
  '/dashboard/$guildId/structure/deploy': typeof DashboardGuildIdStructureDeployRoute
  '/dashboard/$guildId/structure/runs': typeof DashboardGuildIdStructureRunsRoute
  '/dashboard/$guildId/events/': typeof DashboardGuildIdEventsIndexRoute
  '/dashboard/$guildId/general/': typeof DashboardGuildIdGeneralIndexRoute
  '/dashboard/$guildId/messaging/': typeof DashboardGuildIdMessagingIndexRoute
  '/dashboard/$guildId/structure/': typeof DashboardGuildIdStructureIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/.well-known/jwks.json': typeof DotwellKnownJwksDotjsonRoute
  '/dashboard': typeof DashboardIndexRoute
  '/docs': typeof DocsIndexRoute
  '/auth/convex/token': typeof AuthConvexTokenRoute
  '/auth/fluxer/callback': typeof AuthFluxerCallbackRoute
  '/auth/fluxer/login': typeof AuthFluxerLoginRoute
  '/dashboard/$guildId/$': typeof DashboardGuildIdSplatRoute
  '/docs/api/search': typeof DocsApiSearchRoute
  '/docs/topic/$': typeof DocsTopicSplatRoute
  '/dashboard/$guildId': typeof DashboardGuildIdIndexRoute
  '/docs/topic': typeof DocsTopicIndexRoute
  '/dashboard/$guildId/events/audit-events': typeof DashboardGuildIdEventsAuditEventsRoute
  '/dashboard/$guildId/general/command-prefix': typeof DashboardGuildIdGeneralCommandPrefixRoute
  '/dashboard/$guildId/messaging/message-builder': typeof DashboardGuildIdMessagingMessageBuilderRoute
  '/dashboard/$guildId/structure/backups': typeof DashboardGuildIdStructureBackupsRoute
  '/dashboard/$guildId/structure/compare': typeof DashboardGuildIdStructureCompareRoute
  '/dashboard/$guildId/structure/current': typeof DashboardGuildIdStructureCurrentRoute
  '/dashboard/$guildId/structure/deploy': typeof DashboardGuildIdStructureDeployRoute
  '/dashboard/$guildId/structure/runs': typeof DashboardGuildIdStructureRunsRoute
  '/dashboard/$guildId/events': typeof DashboardGuildIdEventsIndexRoute
  '/dashboard/$guildId/general': typeof DashboardGuildIdGeneralIndexRoute
  '/dashboard/$guildId/messaging': typeof DashboardGuildIdMessagingIndexRoute
  '/dashboard/$guildId/structure': typeof DashboardGuildIdStructureIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/.well-known/jwks.json': typeof DotwellKnownJwksDotjsonRoute
  '/dashboard/$guildId': typeof DashboardGuildIdRouteWithChildren
  '/docs/topic': typeof DocsTopicRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/auth/convex/token': typeof AuthConvexTokenRoute
  '/auth/fluxer/callback': typeof AuthFluxerCallbackRoute
  '/auth/fluxer/login': typeof AuthFluxerLoginRoute
  '/dashboard/$guildId/$': typeof DashboardGuildIdSplatRoute
  '/dashboard/$guildId/events': typeof DashboardGuildIdEventsRouteWithChildren
  '/dashboard/$guildId/general': typeof DashboardGuildIdGeneralRouteWithChildren
  '/dashboard/$guildId/messaging': typeof DashboardGuildIdMessagingRouteWithChildren
  '/dashboard/$guildId/structure': typeof DashboardGuildIdStructureRouteWithChildren
  '/docs/api/search': typeof DocsApiSearchRoute
  '/docs/topic/$': typeof DocsTopicSplatRoute
  '/dashboard/$guildId/': typeof DashboardGuildIdIndexRoute
  '/docs/topic/': typeof DocsTopicIndexRoute
  '/dashboard/$guildId/events/audit-events': typeof DashboardGuildIdEventsAuditEventsRoute
  '/dashboard/$guildId/general/command-prefix': typeof DashboardGuildIdGeneralCommandPrefixRoute
  '/dashboard/$guildId/messaging/message-builder': typeof DashboardGuildIdMessagingMessageBuilderRoute
  '/dashboard/$guildId/structure/backups': typeof DashboardGuildIdStructureBackupsRoute
  '/dashboard/$guildId/structure/compare': typeof DashboardGuildIdStructureCompareRoute
  '/dashboard/$guildId/structure/current': typeof DashboardGuildIdStructureCurrentRoute
  '/dashboard/$guildId/structure/deploy': typeof DashboardGuildIdStructureDeployRoute
  '/dashboard/$guildId/structure/runs': typeof DashboardGuildIdStructureRunsRoute
  '/dashboard/$guildId/events/': typeof DashboardGuildIdEventsIndexRoute
  '/dashboard/$guildId/general/': typeof DashboardGuildIdGeneralIndexRoute
  '/dashboard/$guildId/messaging/': typeof DashboardGuildIdMessagingIndexRoute
  '/dashboard/$guildId/structure/': typeof DashboardGuildIdStructureIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/docs'
    | '/.well-known/jwks.json'
    | '/dashboard/$guildId'
    | '/docs/topic'
    | '/dashboard/'
    | '/docs/'
    | '/auth/convex/token'
    | '/auth/fluxer/callback'
    | '/auth/fluxer/login'
    | '/dashboard/$guildId/$'
    | '/dashboard/$guildId/events'
    | '/dashboard/$guildId/general'
    | '/dashboard/$guildId/messaging'
    | '/dashboard/$guildId/structure'
    | '/docs/api/search'
    | '/docs/topic/$'
    | '/dashboard/$guildId/'
    | '/docs/topic/'
    | '/dashboard/$guildId/events/audit-events'
    | '/dashboard/$guildId/general/command-prefix'
    | '/dashboard/$guildId/messaging/message-builder'
    | '/dashboard/$guildId/structure/backups'
    | '/dashboard/$guildId/structure/compare'
    | '/dashboard/$guildId/structure/current'
    | '/dashboard/$guildId/structure/deploy'
    | '/dashboard/$guildId/structure/runs'
    | '/dashboard/$guildId/events/'
    | '/dashboard/$guildId/general/'
    | '/dashboard/$guildId/messaging/'
    | '/dashboard/$guildId/structure/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/.well-known/jwks.json'
    | '/dashboard'
    | '/docs'
    | '/auth/convex/token'
    | '/auth/fluxer/callback'
    | '/auth/fluxer/login'
    | '/dashboard/$guildId/$'
    | '/docs/api/search'
    | '/docs/topic/$'
    | '/dashboard/$guildId'
    | '/docs/topic'
    | '/dashboard/$guildId/events/audit-events'
    | '/dashboard/$guildId/general/command-prefix'
    | '/dashboard/$guildId/messaging/message-builder'
    | '/dashboard/$guildId/structure/backups'
    | '/dashboard/$guildId/structure/compare'
    | '/dashboard/$guildId/structure/current'
    | '/dashboard/$guildId/structure/deploy'
    | '/dashboard/$guildId/structure/runs'
    | '/dashboard/$guildId/events'
    | '/dashboard/$guildId/general'
    | '/dashboard/$guildId/messaging'
    | '/dashboard/$guildId/structure'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/docs'
    | '/.well-known/jwks.json'
    | '/dashboard/$guildId'
    | '/docs/topic'
    | '/dashboard/'
    | '/docs/'
    | '/auth/convex/token'
    | '/auth/fluxer/callback'
    | '/auth/fluxer/login'
    | '/dashboard/$guildId/$'
    | '/dashboard/$guildId/events'
    | '/dashboard/$guildId/general'
    | '/dashboard/$guildId/messaging'
    | '/dashboard/$guildId/structure'
    | '/docs/api/search'
    | '/docs/topic/$'
    | '/dashboard/$guildId/'
    | '/docs/topic/'
    | '/dashboard/$guildId/events/audit-events'
    | '/dashboard/$guildId/general/command-prefix'
    | '/dashboard/$guildId/messaging/message-builder'
    | '/dashboard/$guildId/structure/backups'
    | '/dashboard/$guildId/structure/compare'
    | '/dashboard/$guildId/structure/current'
    | '/dashboard/$guildId/structure/deploy'
    | '/dashboard/$guildId/structure/runs'
    | '/dashboard/$guildId/events/'
    | '/dashboard/$guildId/general/'
    | '/dashboard/$guildId/messaging/'
    | '/dashboard/$guildId/structure/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
  DotwellKnownJwksDotjsonRoute: typeof DotwellKnownJwksDotjsonRoute
  AuthConvexTokenRoute: typeof AuthConvexTokenRoute
  AuthFluxerCallbackRoute: typeof AuthFluxerCallbackRoute
  AuthFluxerLoginRoute: typeof AuthFluxerLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/docs/topic': {
      id: '/docs/topic'
      path: '/topic'
      fullPath: '/docs/topic'
      preLoaderRoute: typeof DocsTopicRouteImport
      parentRoute: typeof DocsRoute
    }
    '/dashboard/$guildId': {
      id: '/dashboard/$guildId'
      path: '/$guildId'
      fullPath: '/dashboard/$guildId'
      preLoaderRoute: typeof DashboardGuildIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/.well-known/jwks.json': {
      id: '/.well-known/jwks.json'
      path: '/.well-known/jwks.json'
      fullPath: '/.well-known/jwks.json'
      preLoaderRoute: typeof DotwellKnownJwksDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/topic/': {
      id: '/docs/topic/'
      path: '/'
      fullPath: '/docs/topic/'
      preLoaderRoute: typeof DocsTopicIndexRouteImport
      parentRoute: typeof DocsTopicRoute
    }
    '/dashboard/$guildId/': {
      id: '/dashboard/$guildId/'
      path: '/'
      fullPath: '/dashboard/$guildId/'
      preLoaderRoute: typeof DashboardGuildIdIndexRouteImport
      parentRoute: typeof DashboardGuildIdRoute
    }
    '/docs/topic/$': {
      id: '/docs/topic/$'
      path: '/$'
      fullPath: '/docs/topic/$'
      preLoaderRoute: typeof DocsTopicSplatRouteImport
      parentRoute: typeof DocsTopicRoute
    }
    '/docs/api/search': {
      id: '/docs/api/search'
      path: '/api/search'
      fullPath: '/docs/api/search'
      preLoaderRoute: typeof DocsApiSearchRouteImport
      parentRoute: typeof DocsRoute
    }
    '/dashboard/$guildId/structure': {
      id: '/dashboard/$guildId/structure'
      path: '/structure'
      fullPath: '/dashboard/$guildId/structure'
      preLoaderRoute: typeof DashboardGuildIdStructureRouteImport
      parentRoute: typeof DashboardGuildIdRoute
    }
    '/dashboard/$guildId/messaging': {
      id: '/dashboard/$guildId/messaging'
      path: '/messaging'
      fullPath: '/dashboard/$guildId/messaging'
      preLoaderRoute: typeof DashboardGuildIdMessagingRouteImport
      parentRoute: typeof DashboardGuildIdRoute
    }
    '/dashboard/$guildId/general': {
      id: '/dashboard/$guildId/general'
      path: '/general'
      fullPath: '/dashboard/$guildId/general'
      preLoaderRoute: typeof DashboardGuildIdGeneralRouteImport
      parentRoute: typeof DashboardGuildIdRoute
    }
    '/dashboard/$guildId/events': {
      id: '/dashboard/$guildId/events'
      path: '/events'
      fullPath: '/dashboard/$guildId/events'
      preLoaderRoute: typeof DashboardGuildIdEventsRouteImport
      parentRoute: typeof DashboardGuildIdRoute
    }
    '/dashboard/$guildId/$': {
      id: '/dashboard/$guildId/$'
      path: '/$'
      fullPath: '/dashboard/$guildId/$'
      preLoaderRoute: typeof DashboardGuildIdSplatRouteImport
      parentRoute: typeof DashboardGuildIdRoute
    }
    '/auth/fluxer/login': {
      id: '/auth/fluxer/login'
      path: '/auth/fluxer/login'
      fullPath: '/auth/fluxer/login'
      preLoaderRoute: typeof AuthFluxerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/fluxer/callback': {
      id: '/auth/fluxer/callback'
      path: '/auth/fluxer/callback'
      fullPath: '/auth/fluxer/callback'
      preLoaderRoute: typeof AuthFluxerCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/convex/token': {
      id: '/auth/convex/token'
      path: '/auth/convex/token'
      fullPath: '/auth/convex/token'
      preLoaderRoute: typeof AuthConvexTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$guildId/structure/': {
      id: '/dashboard/$guildId/structure/'
      path: '/'
      fullPath: '/dashboard/$guildId/structure/'
      preLoaderRoute: typeof DashboardGuildIdStructureIndexRouteImport
      parentRoute: typeof DashboardGuildIdStructureRoute
    }
    '/dashboard/$guildId/messaging/': {
      id: '/dashboard/$guildId/messaging/'
      path: '/'
      fullPath: '/dashboard/$guildId/messaging/'
      preLoaderRoute: typeof DashboardGuildIdMessagingIndexRouteImport
      parentRoute: typeof DashboardGuildIdMessagingRoute
    }
    '/dashboard/$guildId/general/': {
      id: '/dashboard/$guildId/general/'
      path: '/'
      fullPath: '/dashboard/$guildId/general/'
      preLoaderRoute: typeof DashboardGuildIdGeneralIndexRouteImport
      parentRoute: typeof DashboardGuildIdGeneralRoute
    }
    '/dashboard/$guildId/events/': {
      id: '/dashboard/$guildId/events/'
      path: '/'
      fullPath: '/dashboard/$guildId/events/'
      preLoaderRoute: typeof DashboardGuildIdEventsIndexRouteImport
      parentRoute: typeof DashboardGuildIdEventsRoute
    }
    '/dashboard/$guildId/structure/runs': {
      id: '/dashboard/$guildId/structure/runs'
      path: '/runs'
      fullPath: '/dashboard/$guildId/structure/runs'
      preLoaderRoute: typeof DashboardGuildIdStructureRunsRouteImport
      parentRoute: typeof DashboardGuildIdStructureRoute
    }
    '/dashboard/$guildId/structure/deploy': {
      id: '/dashboard/$guildId/structure/deploy'
      path: '/deploy'
      fullPath: '/dashboard/$guildId/structure/deploy'
      preLoaderRoute: typeof DashboardGuildIdStructureDeployRouteImport
      parentRoute: typeof DashboardGuildIdStructureRoute
    }
    '/dashboard/$guildId/structure/current': {
      id: '/dashboard/$guildId/structure/current'
      path: '/current'
      fullPath: '/dashboard/$guildId/structure/current'
      preLoaderRoute: typeof DashboardGuildIdStructureCurrentRouteImport
      parentRoute: typeof DashboardGuildIdStructureRoute
    }
    '/dashboard/$guildId/structure/compare': {
      id: '/dashboard/$guildId/structure/compare'
      path: '/compare'
      fullPath: '/dashboard/$guildId/structure/compare'
      preLoaderRoute: typeof DashboardGuildIdStructureCompareRouteImport
      parentRoute: typeof DashboardGuildIdStructureRoute
    }
    '/dashboard/$guildId/structure/backups': {
      id: '/dashboard/$guildId/structure/backups'
      path: '/backups'
      fullPath: '/dashboard/$guildId/structure/backups'
      preLoaderRoute: typeof DashboardGuildIdStructureBackupsRouteImport
      parentRoute: typeof DashboardGuildIdStructureRoute
    }
    '/dashboard/$guildId/messaging/message-builder': {
      id: '/dashboard/$guildId/messaging/message-builder'
      path: '/message-builder'
      fullPath: '/dashboard/$guildId/messaging/message-builder'
      preLoaderRoute: typeof DashboardGuildIdMessagingMessageBuilderRouteImport
      parentRoute: typeof DashboardGuildIdMessagingRoute
    }
    '/dashboard/$guildId/general/command-prefix': {
      id: '/dashboard/$guildId/general/command-prefix'
      path: '/command-prefix'
      fullPath: '/dashboard/$guildId/general/command-prefix'
      preLoaderRoute: typeof DashboardGuildIdGeneralCommandPrefixRouteImport
      parentRoute: typeof DashboardGuildIdGeneralRoute
    }
    '/dashboard/$guildId/events/audit-events': {
      id: '/dashboard/$guildId/events/audit-events'
      path: '/audit-events'
      fullPath: '/dashboard/$guildId/events/audit-events'
      preLoaderRoute: typeof DashboardGuildIdEventsAuditEventsRouteImport
      parentRoute: typeof DashboardGuildIdEventsRoute
    }
  }
}

interface DashboardGuildIdEventsRouteChildren {
  DashboardGuildIdEventsAuditEventsRoute: typeof DashboardGuildIdEventsAuditEventsRoute
  DashboardGuildIdEventsIndexRoute: typeof DashboardGuildIdEventsIndexRoute
}

const DashboardGuildIdEventsRouteChildren: DashboardGuildIdEventsRouteChildren =
  {
    DashboardGuildIdEventsAuditEventsRoute:
      DashboardGuildIdEventsAuditEventsRoute,
    DashboardGuildIdEventsIndexRoute: DashboardGuildIdEventsIndexRoute,
  }

const DashboardGuildIdEventsRouteWithChildren =
  DashboardGuildIdEventsRoute._addFileChildren(
    DashboardGuildIdEventsRouteChildren,
  )

interface DashboardGuildIdGeneralRouteChildren {
  DashboardGuildIdGeneralCommandPrefixRoute: typeof DashboardGuildIdGeneralCommandPrefixRoute
  DashboardGuildIdGeneralIndexRoute: typeof DashboardGuildIdGeneralIndexRoute
}

const DashboardGuildIdGeneralRouteChildren: DashboardGuildIdGeneralRouteChildren =
  {
    DashboardGuildIdGeneralCommandPrefixRoute:
      DashboardGuildIdGeneralCommandPrefixRoute,
    DashboardGuildIdGeneralIndexRoute: DashboardGuildIdGeneralIndexRoute,
  }

const DashboardGuildIdGeneralRouteWithChildren =
  DashboardGuildIdGeneralRoute._addFileChildren(
    DashboardGuildIdGeneralRouteChildren,
  )

interface DashboardGuildIdMessagingRouteChildren {
  DashboardGuildIdMessagingMessageBuilderRoute: typeof DashboardGuildIdMessagingMessageBuilderRoute
  DashboardGuildIdMessagingIndexRoute: typeof DashboardGuildIdMessagingIndexRoute
}

const DashboardGuildIdMessagingRouteChildren: DashboardGuildIdMessagingRouteChildren =
  {
    DashboardGuildIdMessagingMessageBuilderRoute:
      DashboardGuildIdMessagingMessageBuilderRoute,
    DashboardGuildIdMessagingIndexRoute: DashboardGuildIdMessagingIndexRoute,
  }

const DashboardGuildIdMessagingRouteWithChildren =
  DashboardGuildIdMessagingRoute._addFileChildren(
    DashboardGuildIdMessagingRouteChildren,
  )

interface DashboardGuildIdStructureRouteChildren {
  DashboardGuildIdStructureBackupsRoute: typeof DashboardGuildIdStructureBackupsRoute
  DashboardGuildIdStructureCompareRoute: typeof DashboardGuildIdStructureCompareRoute
  DashboardGuildIdStructureCurrentRoute: typeof DashboardGuildIdStructureCurrentRoute
  DashboardGuildIdStructureDeployRoute: typeof DashboardGuildIdStructureDeployRoute
  DashboardGuildIdStructureRunsRoute: typeof DashboardGuildIdStructureRunsRoute
  DashboardGuildIdStructureIndexRoute: typeof DashboardGuildIdStructureIndexRoute
}

const DashboardGuildIdStructureRouteChildren: DashboardGuildIdStructureRouteChildren =
  {
    DashboardGuildIdStructureBackupsRoute:
      DashboardGuildIdStructureBackupsRoute,
    DashboardGuildIdStructureCompareRoute:
      DashboardGuildIdStructureCompareRoute,
    DashboardGuildIdStructureCurrentRoute:
      DashboardGuildIdStructureCurrentRoute,
    DashboardGuildIdStructureDeployRoute: DashboardGuildIdStructureDeployRoute,
    DashboardGuildIdStructureRunsRoute: DashboardGuildIdStructureRunsRoute,
    DashboardGuildIdStructureIndexRoute: DashboardGuildIdStructureIndexRoute,
  }

const DashboardGuildIdStructureRouteWithChildren =
  DashboardGuildIdStructureRoute._addFileChildren(
    DashboardGuildIdStructureRouteChildren,
  )

interface DashboardGuildIdRouteChildren {
  DashboardGuildIdSplatRoute: typeof DashboardGuildIdSplatRoute
  DashboardGuildIdEventsRoute: typeof DashboardGuildIdEventsRouteWithChildren
  DashboardGuildIdGeneralRoute: typeof DashboardGuildIdGeneralRouteWithChildren
  DashboardGuildIdMessagingRoute: typeof DashboardGuildIdMessagingRouteWithChildren
  DashboardGuildIdStructureRoute: typeof DashboardGuildIdStructureRouteWithChildren
  DashboardGuildIdIndexRoute: typeof DashboardGuildIdIndexRoute
}

const DashboardGuildIdRouteChildren: DashboardGuildIdRouteChildren = {
  DashboardGuildIdSplatRoute: DashboardGuildIdSplatRoute,
  DashboardGuildIdEventsRoute: DashboardGuildIdEventsRouteWithChildren,
  DashboardGuildIdGeneralRoute: DashboardGuildIdGeneralRouteWithChildren,
  DashboardGuildIdMessagingRoute: DashboardGuildIdMessagingRouteWithChildren,
  DashboardGuildIdStructureRoute: DashboardGuildIdStructureRouteWithChildren,
  DashboardGuildIdIndexRoute: DashboardGuildIdIndexRoute,
}

const DashboardGuildIdRouteWithChildren =
  DashboardGuildIdRoute._addFileChildren(DashboardGuildIdRouteChildren)

interface DashboardRouteChildren {
  DashboardGuildIdRoute: typeof DashboardGuildIdRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardGuildIdRoute: DashboardGuildIdRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface DocsTopicRouteChildren {
  DocsTopicSplatRoute: typeof DocsTopicSplatRoute
  DocsTopicIndexRoute: typeof DocsTopicIndexRoute
}

const DocsTopicRouteChildren: DocsTopicRouteChildren = {
  DocsTopicSplatRoute: DocsTopicSplatRoute,
  DocsTopicIndexRoute: DocsTopicIndexRoute,
}

const DocsTopicRouteWithChildren = DocsTopicRoute._addFileChildren(
  DocsTopicRouteChildren,
)

interface DocsRouteChildren {
  DocsTopicRoute: typeof DocsTopicRouteWithChildren
  DocsIndexRoute: typeof DocsIndexRoute
  DocsApiSearchRoute: typeof DocsApiSearchRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsTopicRoute: DocsTopicRouteWithChildren,
  DocsIndexRoute: DocsIndexRoute,
  DocsApiSearchRoute: DocsApiSearchRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
  DotwellKnownJwksDotjsonRoute: DotwellKnownJwksDotjsonRoute,
  AuthConvexTokenRoute: AuthConvexTokenRoute,
  AuthFluxerCallbackRoute: AuthFluxerCallbackRoute,
  AuthFluxerLoginRoute: AuthFluxerLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
