/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DocsTopicRouteImport } from './routes/docs/topic'
import { Route as DashboardGuildIdRouteImport } from './routes/dashboard.$guildId'
import { Route as DocsTopicIndexRouteImport } from './routes/docs/topic/index'
import { Route as DashboardGuildIdIndexRouteImport } from './routes/dashboard/$guildId/index'
import { Route as DocsTopicSplatRouteImport } from './routes/docs/topic/$'
import { Route as DocsApiSearchRouteImport } from './routes/docs/api/search'
import { Route as DashboardGuildIdStructureRouteImport } from './routes/dashboard/$guildId/structure'
import { Route as DashboardGuildIdModerationRouteImport } from './routes/dashboard/$guildId/moderation'
import { Route as DashboardGuildIdMessagingRouteImport } from './routes/dashboard/$guildId/messaging'
import { Route as DashboardGuildIdLoggingRouteImport } from './routes/dashboard/$guildId/logging'
import { Route as DashboardGuildIdInvitesRouteImport } from './routes/dashboard/$guildId/invites'
import { Route as DashboardGuildIdGeneralRouteImport } from './routes/dashboard/$guildId/general'
import { Route as DashboardGuildIdEventsRouteImport } from './routes/dashboard.$guildId.events'
import { Route as DashboardGuildIdCommunityRouteImport } from './routes/dashboard/$guildId/community'
import { Route as DashboardGuildIdAuditRouteImport } from './routes/dashboard/$guildId/audit'
import { Route as DashboardGuildIdAccessRouteImport } from './routes/dashboard/$guildId/access'
import { Route as AuthFluxerLoginRouteImport } from './routes/auth/fluxer/login'
import { Route as AuthFluxerCallbackRouteImport } from './routes/auth/fluxer/callback'

const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DocsTopicRoute = DocsTopicRouteImport.update({
  id: '/topic',
  path: '/topic',
  getParentRoute: () => DocsRoute,
} as any)
const DashboardGuildIdRoute = DashboardGuildIdRouteImport.update({
  id: '/$guildId',
  path: '/$guildId',
  getParentRoute: () => DashboardRoute,
} as any)
const DocsTopicIndexRoute = DocsTopicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsTopicRoute,
} as any)
const DashboardGuildIdIndexRoute = DashboardGuildIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardGuildIdRoute,
} as any)
const DocsTopicSplatRoute = DocsTopicSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DocsTopicRoute,
} as any)
const DocsApiSearchRoute = DocsApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => DocsRoute,
} as any)
const DashboardGuildIdStructureRoute =
  DashboardGuildIdStructureRouteImport.update({
    id: '/structure',
    path: '/structure',
    getParentRoute: () => DashboardGuildIdRoute,
  } as any)
const DashboardGuildIdModerationRoute =
  DashboardGuildIdModerationRouteImport.update({
    id: '/moderation',
    path: '/moderation',
    getParentRoute: () => DashboardGuildIdRoute,
  } as any)
const DashboardGuildIdMessagingRoute =
  DashboardGuildIdMessagingRouteImport.update({
    id: '/messaging',
    path: '/messaging',
    getParentRoute: () => DashboardGuildIdRoute,
  } as any)
const DashboardGuildIdLoggingRoute = DashboardGuildIdLoggingRouteImport.update({
  id: '/logging',
  path: '/logging',
  getParentRoute: () => DashboardGuildIdRoute,
} as any)
const DashboardGuildIdInvitesRoute = DashboardGuildIdInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => DashboardGuildIdRoute,
} as any)
const DashboardGuildIdGeneralRoute = DashboardGuildIdGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => DashboardGuildIdRoute,
} as any)
const DashboardGuildIdEventsRoute = DashboardGuildIdEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => DashboardGuildIdRoute,
} as any)
const DashboardGuildIdCommunityRoute =
  DashboardGuildIdCommunityRouteImport.update({
    id: '/community',
    path: '/community',
    getParentRoute: () => DashboardGuildIdRoute,
  } as any)
const DashboardGuildIdAuditRoute = DashboardGuildIdAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => DashboardGuildIdRoute,
} as any)
const DashboardGuildIdAccessRoute = DashboardGuildIdAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => DashboardGuildIdRoute,
} as any)
const AuthFluxerLoginRoute = AuthFluxerLoginRouteImport.update({
  id: '/auth/fluxer/login',
  path: '/auth/fluxer/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthFluxerCallbackRoute = AuthFluxerCallbackRouteImport.update({
  id: '/auth/fluxer/callback',
  path: '/auth/fluxer/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/dashboard/$guildId': typeof DashboardGuildIdRouteWithChildren
  '/docs/topic': typeof DocsTopicRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/auth/fluxer/callback': typeof AuthFluxerCallbackRoute
  '/auth/fluxer/login': typeof AuthFluxerLoginRoute
  '/dashboard/$guildId/access': typeof DashboardGuildIdAccessRoute
  '/dashboard/$guildId/audit': typeof DashboardGuildIdAuditRoute
  '/dashboard/$guildId/community': typeof DashboardGuildIdCommunityRoute
  '/dashboard/$guildId/events': typeof DashboardGuildIdEventsRoute
  '/dashboard/$guildId/general': typeof DashboardGuildIdGeneralRoute
  '/dashboard/$guildId/invites': typeof DashboardGuildIdInvitesRoute
  '/dashboard/$guildId/logging': typeof DashboardGuildIdLoggingRoute
  '/dashboard/$guildId/messaging': typeof DashboardGuildIdMessagingRoute
  '/dashboard/$guildId/moderation': typeof DashboardGuildIdModerationRoute
  '/dashboard/$guildId/structure': typeof DashboardGuildIdStructureRoute
  '/docs/api/search': typeof DocsApiSearchRoute
  '/docs/topic/$': typeof DocsTopicSplatRoute
  '/dashboard/$guildId/': typeof DashboardGuildIdIndexRoute
  '/docs/topic/': typeof DocsTopicIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/docs': typeof DocsIndexRoute
  '/auth/fluxer/callback': typeof AuthFluxerCallbackRoute
  '/auth/fluxer/login': typeof AuthFluxerLoginRoute
  '/dashboard/$guildId/access': typeof DashboardGuildIdAccessRoute
  '/dashboard/$guildId/audit': typeof DashboardGuildIdAuditRoute
  '/dashboard/$guildId/community': typeof DashboardGuildIdCommunityRoute
  '/dashboard/$guildId/events': typeof DashboardGuildIdEventsRoute
  '/dashboard/$guildId/general': typeof DashboardGuildIdGeneralRoute
  '/dashboard/$guildId/invites': typeof DashboardGuildIdInvitesRoute
  '/dashboard/$guildId/logging': typeof DashboardGuildIdLoggingRoute
  '/dashboard/$guildId/messaging': typeof DashboardGuildIdMessagingRoute
  '/dashboard/$guildId/moderation': typeof DashboardGuildIdModerationRoute
  '/dashboard/$guildId/structure': typeof DashboardGuildIdStructureRoute
  '/docs/api/search': typeof DocsApiSearchRoute
  '/docs/topic/$': typeof DocsTopicSplatRoute
  '/dashboard/$guildId': typeof DashboardGuildIdIndexRoute
  '/docs/topic': typeof DocsTopicIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/dashboard/$guildId': typeof DashboardGuildIdRouteWithChildren
  '/docs/topic': typeof DocsTopicRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/auth/fluxer/callback': typeof AuthFluxerCallbackRoute
  '/auth/fluxer/login': typeof AuthFluxerLoginRoute
  '/dashboard/$guildId/access': typeof DashboardGuildIdAccessRoute
  '/dashboard/$guildId/audit': typeof DashboardGuildIdAuditRoute
  '/dashboard/$guildId/community': typeof DashboardGuildIdCommunityRoute
  '/dashboard/$guildId/events': typeof DashboardGuildIdEventsRoute
  '/dashboard/$guildId/general': typeof DashboardGuildIdGeneralRoute
  '/dashboard/$guildId/invites': typeof DashboardGuildIdInvitesRoute
  '/dashboard/$guildId/logging': typeof DashboardGuildIdLoggingRoute
  '/dashboard/$guildId/messaging': typeof DashboardGuildIdMessagingRoute
  '/dashboard/$guildId/moderation': typeof DashboardGuildIdModerationRoute
  '/dashboard/$guildId/structure': typeof DashboardGuildIdStructureRoute
  '/docs/api/search': typeof DocsApiSearchRoute
  '/docs/topic/$': typeof DocsTopicSplatRoute
  '/dashboard/$guildId/': typeof DashboardGuildIdIndexRoute
  '/docs/topic/': typeof DocsTopicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/docs'
    | '/dashboard/$guildId'
    | '/docs/topic'
    | '/dashboard/'
    | '/docs/'
    | '/auth/fluxer/callback'
    | '/auth/fluxer/login'
    | '/dashboard/$guildId/access'
    | '/dashboard/$guildId/audit'
    | '/dashboard/$guildId/community'
    | '/dashboard/$guildId/events'
    | '/dashboard/$guildId/general'
    | '/dashboard/$guildId/invites'
    | '/dashboard/$guildId/logging'
    | '/dashboard/$guildId/messaging'
    | '/dashboard/$guildId/moderation'
    | '/dashboard/$guildId/structure'
    | '/docs/api/search'
    | '/docs/topic/$'
    | '/dashboard/$guildId/'
    | '/docs/topic/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/docs'
    | '/auth/fluxer/callback'
    | '/auth/fluxer/login'
    | '/dashboard/$guildId/access'
    | '/dashboard/$guildId/audit'
    | '/dashboard/$guildId/community'
    | '/dashboard/$guildId/events'
    | '/dashboard/$guildId/general'
    | '/dashboard/$guildId/invites'
    | '/dashboard/$guildId/logging'
    | '/dashboard/$guildId/messaging'
    | '/dashboard/$guildId/moderation'
    | '/dashboard/$guildId/structure'
    | '/docs/api/search'
    | '/docs/topic/$'
    | '/dashboard/$guildId'
    | '/docs/topic'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/docs'
    | '/dashboard/$guildId'
    | '/docs/topic'
    | '/dashboard/'
    | '/docs/'
    | '/auth/fluxer/callback'
    | '/auth/fluxer/login'
    | '/dashboard/$guildId/access'
    | '/dashboard/$guildId/audit'
    | '/dashboard/$guildId/community'
    | '/dashboard/$guildId/events'
    | '/dashboard/$guildId/general'
    | '/dashboard/$guildId/invites'
    | '/dashboard/$guildId/logging'
    | '/dashboard/$guildId/messaging'
    | '/dashboard/$guildId/moderation'
    | '/dashboard/$guildId/structure'
    | '/docs/api/search'
    | '/docs/topic/$'
    | '/dashboard/$guildId/'
    | '/docs/topic/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
  AuthFluxerCallbackRoute: typeof AuthFluxerCallbackRoute
  AuthFluxerLoginRoute: typeof AuthFluxerLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/docs/topic': {
      id: '/docs/topic'
      path: '/topic'
      fullPath: '/docs/topic'
      preLoaderRoute: typeof DocsTopicRouteImport
      parentRoute: typeof DocsRoute
    }
    '/dashboard/$guildId': {
      id: '/dashboard/$guildId'
      path: '/$guildId'
      fullPath: '/dashboard/$guildId'
      preLoaderRoute: typeof DashboardGuildIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/docs/topic/': {
      id: '/docs/topic/'
      path: '/'
      fullPath: '/docs/topic/'
      preLoaderRoute: typeof DocsTopicIndexRouteImport
      parentRoute: typeof DocsTopicRoute
    }
    '/dashboard/$guildId/': {
      id: '/dashboard/$guildId/'
      path: '/'
      fullPath: '/dashboard/$guildId/'
      preLoaderRoute: typeof DashboardGuildIdIndexRouteImport
      parentRoute: typeof DashboardGuildIdRoute
    }
    '/docs/topic/$': {
      id: '/docs/topic/$'
      path: '/$'
      fullPath: '/docs/topic/$'
      preLoaderRoute: typeof DocsTopicSplatRouteImport
      parentRoute: typeof DocsTopicRoute
    }
    '/docs/api/search': {
      id: '/docs/api/search'
      path: '/api/search'
      fullPath: '/docs/api/search'
      preLoaderRoute: typeof DocsApiSearchRouteImport
      parentRoute: typeof DocsRoute
    }
    '/dashboard/$guildId/structure': {
      id: '/dashboard/$guildId/structure'
      path: '/structure'
      fullPath: '/dashboard/$guildId/structure'
      preLoaderRoute: typeof DashboardGuildIdStructureRouteImport
      parentRoute: typeof DashboardGuildIdRoute
    }
    '/dashboard/$guildId/moderation': {
      id: '/dashboard/$guildId/moderation'
      path: '/moderation'
      fullPath: '/dashboard/$guildId/moderation'
      preLoaderRoute: typeof DashboardGuildIdModerationRouteImport
      parentRoute: typeof DashboardGuildIdRoute
    }
    '/dashboard/$guildId/messaging': {
      id: '/dashboard/$guildId/messaging'
      path: '/messaging'
      fullPath: '/dashboard/$guildId/messaging'
      preLoaderRoute: typeof DashboardGuildIdMessagingRouteImport
      parentRoute: typeof DashboardGuildIdRoute
    }
    '/dashboard/$guildId/logging': {
      id: '/dashboard/$guildId/logging'
      path: '/logging'
      fullPath: '/dashboard/$guildId/logging'
      preLoaderRoute: typeof DashboardGuildIdLoggingRouteImport
      parentRoute: typeof DashboardGuildIdRoute
    }
    '/dashboard/$guildId/invites': {
      id: '/dashboard/$guildId/invites'
      path: '/invites'
      fullPath: '/dashboard/$guildId/invites'
      preLoaderRoute: typeof DashboardGuildIdInvitesRouteImport
      parentRoute: typeof DashboardGuildIdRoute
    }
    '/dashboard/$guildId/general': {
      id: '/dashboard/$guildId/general'
      path: '/general'
      fullPath: '/dashboard/$guildId/general'
      preLoaderRoute: typeof DashboardGuildIdGeneralRouteImport
      parentRoute: typeof DashboardGuildIdRoute
    }
    '/dashboard/$guildId/events': {
      id: '/dashboard/$guildId/events'
      path: '/events'
      fullPath: '/dashboard/$guildId/events'
      preLoaderRoute: typeof DashboardGuildIdEventsRouteImport
      parentRoute: typeof DashboardGuildIdRoute
    }
    '/dashboard/$guildId/community': {
      id: '/dashboard/$guildId/community'
      path: '/community'
      fullPath: '/dashboard/$guildId/community'
      preLoaderRoute: typeof DashboardGuildIdCommunityRouteImport
      parentRoute: typeof DashboardGuildIdRoute
    }
    '/dashboard/$guildId/audit': {
      id: '/dashboard/$guildId/audit'
      path: '/audit'
      fullPath: '/dashboard/$guildId/audit'
      preLoaderRoute: typeof DashboardGuildIdAuditRouteImport
      parentRoute: typeof DashboardGuildIdRoute
    }
    '/dashboard/$guildId/access': {
      id: '/dashboard/$guildId/access'
      path: '/access'
      fullPath: '/dashboard/$guildId/access'
      preLoaderRoute: typeof DashboardGuildIdAccessRouteImport
      parentRoute: typeof DashboardGuildIdRoute
    }
    '/auth/fluxer/login': {
      id: '/auth/fluxer/login'
      path: '/auth/fluxer/login'
      fullPath: '/auth/fluxer/login'
      preLoaderRoute: typeof AuthFluxerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/fluxer/callback': {
      id: '/auth/fluxer/callback'
      path: '/auth/fluxer/callback'
      fullPath: '/auth/fluxer/callback'
      preLoaderRoute: typeof AuthFluxerCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardGuildIdRouteChildren {
  DashboardGuildIdAccessRoute: typeof DashboardGuildIdAccessRoute
  DashboardGuildIdAuditRoute: typeof DashboardGuildIdAuditRoute
  DashboardGuildIdCommunityRoute: typeof DashboardGuildIdCommunityRoute
  DashboardGuildIdEventsRoute: typeof DashboardGuildIdEventsRoute
  DashboardGuildIdGeneralRoute: typeof DashboardGuildIdGeneralRoute
  DashboardGuildIdInvitesRoute: typeof DashboardGuildIdInvitesRoute
  DashboardGuildIdLoggingRoute: typeof DashboardGuildIdLoggingRoute
  DashboardGuildIdMessagingRoute: typeof DashboardGuildIdMessagingRoute
  DashboardGuildIdModerationRoute: typeof DashboardGuildIdModerationRoute
  DashboardGuildIdStructureRoute: typeof DashboardGuildIdStructureRoute
  DashboardGuildIdIndexRoute: typeof DashboardGuildIdIndexRoute
}

const DashboardGuildIdRouteChildren: DashboardGuildIdRouteChildren = {
  DashboardGuildIdAccessRoute: DashboardGuildIdAccessRoute,
  DashboardGuildIdAuditRoute: DashboardGuildIdAuditRoute,
  DashboardGuildIdCommunityRoute: DashboardGuildIdCommunityRoute,
  DashboardGuildIdEventsRoute: DashboardGuildIdEventsRoute,
  DashboardGuildIdGeneralRoute: DashboardGuildIdGeneralRoute,
  DashboardGuildIdInvitesRoute: DashboardGuildIdInvitesRoute,
  DashboardGuildIdLoggingRoute: DashboardGuildIdLoggingRoute,
  DashboardGuildIdMessagingRoute: DashboardGuildIdMessagingRoute,
  DashboardGuildIdModerationRoute: DashboardGuildIdModerationRoute,
  DashboardGuildIdStructureRoute: DashboardGuildIdStructureRoute,
  DashboardGuildIdIndexRoute: DashboardGuildIdIndexRoute,
}

const DashboardGuildIdRouteWithChildren =
  DashboardGuildIdRoute._addFileChildren(DashboardGuildIdRouteChildren)

interface DashboardRouteChildren {
  DashboardGuildIdRoute: typeof DashboardGuildIdRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardGuildIdRoute: DashboardGuildIdRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface DocsTopicRouteChildren {
  DocsTopicSplatRoute: typeof DocsTopicSplatRoute
  DocsTopicIndexRoute: typeof DocsTopicIndexRoute
}

const DocsTopicRouteChildren: DocsTopicRouteChildren = {
  DocsTopicSplatRoute: DocsTopicSplatRoute,
  DocsTopicIndexRoute: DocsTopicIndexRoute,
}

const DocsTopicRouteWithChildren = DocsTopicRoute._addFileChildren(
  DocsTopicRouteChildren,
)

interface DocsRouteChildren {
  DocsTopicRoute: typeof DocsTopicRouteWithChildren
  DocsIndexRoute: typeof DocsIndexRoute
  DocsApiSearchRoute: typeof DocsApiSearchRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsTopicRoute: DocsTopicRouteWithChildren,
  DocsIndexRoute: DocsIndexRoute,
  DocsApiSearchRoute: DocsApiSearchRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
  AuthFluxerCallbackRoute: AuthFluxerCallbackRoute,
  AuthFluxerLoginRoute: AuthFluxerLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
