/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DocsTopicRouteImport } from './routes/docs/topic'
import { Route as DashboardGuildIdRouteImport } from './routes/dashboard.$guildId'
import { Route as DocsTopicIndexRouteImport } from './routes/docs/topic/index'
import { Route as DocsTopicSplatRouteImport } from './routes/docs/topic/$'
import { Route as DocsApiSearchRouteImport } from './routes/docs/api/search'
import { Route as AuthFluxerLoginRouteImport } from './routes/auth/fluxer/login'
import { Route as AuthFluxerCallbackRouteImport } from './routes/auth/fluxer/callback'

const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DocsTopicRoute = DocsTopicRouteImport.update({
  id: '/topic',
  path: '/topic',
  getParentRoute: () => DocsRoute,
} as any)
const DashboardGuildIdRoute = DashboardGuildIdRouteImport.update({
  id: '/$guildId',
  path: '/$guildId',
  getParentRoute: () => DashboardRoute,
} as any)
const DocsTopicIndexRoute = DocsTopicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsTopicRoute,
} as any)
const DocsTopicSplatRoute = DocsTopicSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DocsTopicRoute,
} as any)
const DocsApiSearchRoute = DocsApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => DocsRoute,
} as any)
const AuthFluxerLoginRoute = AuthFluxerLoginRouteImport.update({
  id: '/auth/fluxer/login',
  path: '/auth/fluxer/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthFluxerCallbackRoute = AuthFluxerCallbackRouteImport.update({
  id: '/auth/fluxer/callback',
  path: '/auth/fluxer/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/dashboard/$guildId': typeof DashboardGuildIdRoute
  '/docs/topic': typeof DocsTopicRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/auth/fluxer/callback': typeof AuthFluxerCallbackRoute
  '/auth/fluxer/login': typeof AuthFluxerLoginRoute
  '/docs/api/search': typeof DocsApiSearchRoute
  '/docs/topic/$': typeof DocsTopicSplatRoute
  '/docs/topic/': typeof DocsTopicIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/$guildId': typeof DashboardGuildIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/docs': typeof DocsIndexRoute
  '/auth/fluxer/callback': typeof AuthFluxerCallbackRoute
  '/auth/fluxer/login': typeof AuthFluxerLoginRoute
  '/docs/api/search': typeof DocsApiSearchRoute
  '/docs/topic/$': typeof DocsTopicSplatRoute
  '/docs/topic': typeof DocsTopicIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/dashboard/$guildId': typeof DashboardGuildIdRoute
  '/docs/topic': typeof DocsTopicRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/auth/fluxer/callback': typeof AuthFluxerCallbackRoute
  '/auth/fluxer/login': typeof AuthFluxerLoginRoute
  '/docs/api/search': typeof DocsApiSearchRoute
  '/docs/topic/$': typeof DocsTopicSplatRoute
  '/docs/topic/': typeof DocsTopicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/docs'
    | '/dashboard/$guildId'
    | '/docs/topic'
    | '/dashboard/'
    | '/docs/'
    | '/auth/fluxer/callback'
    | '/auth/fluxer/login'
    | '/docs/api/search'
    | '/docs/topic/$'
    | '/docs/topic/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/$guildId'
    | '/dashboard'
    | '/docs'
    | '/auth/fluxer/callback'
    | '/auth/fluxer/login'
    | '/docs/api/search'
    | '/docs/topic/$'
    | '/docs/topic'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/docs'
    | '/dashboard/$guildId'
    | '/docs/topic'
    | '/dashboard/'
    | '/docs/'
    | '/auth/fluxer/callback'
    | '/auth/fluxer/login'
    | '/docs/api/search'
    | '/docs/topic/$'
    | '/docs/topic/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
  AuthFluxerCallbackRoute: typeof AuthFluxerCallbackRoute
  AuthFluxerLoginRoute: typeof AuthFluxerLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/docs/topic': {
      id: '/docs/topic'
      path: '/topic'
      fullPath: '/docs/topic'
      preLoaderRoute: typeof DocsTopicRouteImport
      parentRoute: typeof DocsRoute
    }
    '/dashboard/$guildId': {
      id: '/dashboard/$guildId'
      path: '/$guildId'
      fullPath: '/dashboard/$guildId'
      preLoaderRoute: typeof DashboardGuildIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/docs/topic/': {
      id: '/docs/topic/'
      path: '/'
      fullPath: '/docs/topic/'
      preLoaderRoute: typeof DocsTopicIndexRouteImport
      parentRoute: typeof DocsTopicRoute
    }
    '/docs/topic/$': {
      id: '/docs/topic/$'
      path: '/$'
      fullPath: '/docs/topic/$'
      preLoaderRoute: typeof DocsTopicSplatRouteImport
      parentRoute: typeof DocsTopicRoute
    }
    '/docs/api/search': {
      id: '/docs/api/search'
      path: '/api/search'
      fullPath: '/docs/api/search'
      preLoaderRoute: typeof DocsApiSearchRouteImport
      parentRoute: typeof DocsRoute
    }
    '/auth/fluxer/login': {
      id: '/auth/fluxer/login'
      path: '/auth/fluxer/login'
      fullPath: '/auth/fluxer/login'
      preLoaderRoute: typeof AuthFluxerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/fluxer/callback': {
      id: '/auth/fluxer/callback'
      path: '/auth/fluxer/callback'
      fullPath: '/auth/fluxer/callback'
      preLoaderRoute: typeof AuthFluxerCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardGuildIdRoute: typeof DashboardGuildIdRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardGuildIdRoute: DashboardGuildIdRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface DocsTopicRouteChildren {
  DocsTopicSplatRoute: typeof DocsTopicSplatRoute
  DocsTopicIndexRoute: typeof DocsTopicIndexRoute
}

const DocsTopicRouteChildren: DocsTopicRouteChildren = {
  DocsTopicSplatRoute: DocsTopicSplatRoute,
  DocsTopicIndexRoute: DocsTopicIndexRoute,
}

const DocsTopicRouteWithChildren = DocsTopicRoute._addFileChildren(
  DocsTopicRouteChildren,
)

interface DocsRouteChildren {
  DocsTopicRoute: typeof DocsTopicRouteWithChildren
  DocsIndexRoute: typeof DocsIndexRoute
  DocsApiSearchRoute: typeof DocsApiSearchRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsTopicRoute: DocsTopicRouteWithChildren,
  DocsIndexRoute: DocsIndexRoute,
  DocsApiSearchRoute: DocsApiSearchRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
  AuthFluxerCallbackRoute: AuthFluxerCallbackRoute,
  AuthFluxerLoginRoute: AuthFluxerLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
