// Every backend request the bot makes, by path. Each path names one public function of the backend's botService module,
// whose name joins the path segments in camel case, so "/general/nickname-result" is botService:generalNicknameResult.
// Queries stay queries and mutations stay mutations. A backend test checks this table against botService.ts, so a new
// backend entry point is one line here and one export there. Mutations answer { value, dueIn }, see backend-http.ts
export const backendRoutes = {
    "/service/scope": "query",
    "/service/installations/list": "query",
    "/service/installations/join": "mutation",
    "/service/installations/leave": "mutation",
    "/service/work": "query",
    // Subscribed by the work dispatcher rather than requested
    "/service/work-signal": "query",
    "/service/ticket-intakes": "query",
    "/service/usage": "mutation",
    "/service/member-data/list": "query",
    "/service/member-data/servers": "query",
    "/service/member-data/export": "query",
    "/service/member-data/delete": "mutation",
    "/afk/set": "mutation",
    "/afk/observe": "mutation",
    "/general/get": "query",
    "/general/manage": "mutation",
    "/general/nickname": "mutation",
    "/general/nickname-result": "mutation",
    "/setup/status": "query",
    "/setup/ready": "query",
    "/setup/record": "mutation",
    "/private-data/ready": "query",
    "/private-data/record": "mutation",
    "/responses/manage": "mutation",
    "/responses/evaluate": "mutation",
    "/moderation/query": "query",
    "/moderation/gate": "query",
    "/moderation/manage": "mutation",
    "/moderation/evaluate": "mutation",
    "/moderation/join": "mutation",
    "/moderation/outcome": "mutation",
    "/moderation/log-outcome": "mutation",
    "/moderation/notice-outcome": "mutation",
    "/moderation/reconcile": "mutation",
    "/moderation/observe": "mutation",
    "/appeals/member": "mutation",
    "/appeals/staff": "mutation",
    "/publishing/query": "query",
    "/publishing/manage": "mutation",
    "/publishing/dispatch": "mutation",
    "/publishing/outcome": "mutation",
    "/publishing/reconcile": "mutation",
    "/publishing/observe": "mutation",
    "/schedules/query": "query",
    "/schedules/manage": "mutation",
    "/schedules/delivery": "mutation",
    "/roles/query": "query",
    "/roles/member-query": "query",
    "/roles/policy": "query",
    "/roles/manage": "mutation",
    "/roles/reaction-jobs": "mutation",
    "/roles/evaluate": "mutation",
    "/roles/dispatch": "mutation",
    "/roles/outcome": "mutation",
    "/roles/reconcile": "mutation",
    "/roles/observe": "mutation",
    "/greetings/query": "query",
    "/greetings/member": "query",
    "/greetings/pending": "query",
    "/greetings/manage": "mutation",
    "/greetings/observe": "mutation",
    "/greetings/discover": "mutation",
    "/greetings/reserve": "mutation",
    "/greetings/dispatch": "mutation",
    "/greetings/outcome": "mutation",
    "/greetings/defer": "mutation",
    "/tickets/query": "query",
    "/tickets/manage": "mutation",
    "/tickets/intake": "mutation",
    "/tickets/transcript": "mutation",
    "/tickets/dispatch": "mutation",
    "/tickets/outcome": "mutation",
    "/tickets/reconcile": "mutation",
    "/levels/query": "query",
    "/levels/preflight": "query",
    "/levels/manage": "mutation",
    "/levels/award": "mutation",
    "/levels/work": "mutation",
    "/events/query": "query",
    "/events/manage": "mutation",
    "/events/rsvp": "mutation",
    "/events/work": "mutation",
    "/events/delivery": "mutation",
    "/milestones/query": "query",
    "/milestones/manage": "mutation",
    "/milestones/personal": "mutation",
    "/milestones/delivery": "mutation",
    "/suggestions/query": "query",
    "/suggestions/manage": "mutation",
    "/suggestions/member": "mutation",
    "/suggestions/work": "mutation",
    "/cleanup/query": "query",
    "/cleanup/manage": "mutation",
    "/cleanup/work": "mutation",
    "/voice/query": "query",
    "/voice/manage": "mutation",
    "/voice/rooms": "mutation",
    "/metadata-logs/query": "query",
    "/metadata-logs/manage": "mutation",
    "/metadata-logs/admit": "mutation",
    "/metadata-logs/work": "mutation",
    "/analytics/settings": "query",
    "/analytics/summary": "query",
    "/analytics/manage": "mutation",
    "/analytics/record": "mutation",
    "/backup/snapshot": "query",
    "/backup/query": "query",
    "/backup/manage": "mutation",
    "/backup/work": "mutation",
    "/dashboard-metadata/ready": "query",
    "/dashboard-metadata/execute": "mutation",
    "/dashboard-metadata/fail": "mutation",
    "/dashboard-configuration/ready": "query",
    "/dashboard-configuration/execute": "mutation",
    "/dashboard-configuration/fail": "mutation",
    "/dashboard-messages/ready": "query",
    "/dashboard-messages/reserve": "mutation",
    "/dashboard-messages/complete": "mutation",
    "/dashboard-messages/fail": "mutation",
    "/dashboard-roles/ready": "query",
    "/dashboard-roles/execute": "mutation",
    "/dashboard-roles/reserve": "mutation",
    "/dashboard-roles/complete": "mutation",
    "/dashboard-roles/fail": "mutation",
    "/rolepicker/settings": "query",
    "/rolepicker/manage": "mutation",
    "/rolepicker/ready": "query",
    "/rolepicker/start": "mutation",
    "/rolepicker/complete": "mutation",
    "/rolepicker/fail": "mutation",
    "/verification/request": "query",
    "/verification/issue": "mutation",
    "/verification/ready": "mutation",
    "/verification/claim": "mutation",
    "/verification/delivery": "mutation",
    "/verification/review": "mutation",
} as const satisfies Record<string, "query" | "mutation">

export type BackendPath = keyof typeof backendRoutes
export function isBackendPath(path: string): path is BackendPath {
    return Object.hasOwn(backendRoutes, path)
}
export function backendFunction(path: BackendPath) {
    return `botService:${path.split(/[/-]/).filter(Boolean).map((part, index) => index ? part[0]!.toUpperCase() + part.slice(1) : part).join("")}`
}
