// Runtime database boundary. App code imports Convex-backed operations and
// app-facing type contracts from here.
export {
    STRUCTURE_IMPORT_EXPORT_FEATURE,
    structureAuditActions,
    structureBackupSources,
    structureBackupStatuses,
    structureScheduledDriftStatuses,
    structureImportActionAttemptStates,
    structureImportExecutionStatuses,
    structureImportExecutionPhases,
    structureImportRunStatuses,
} from './contracts-structure.js';
export type {
    BotActionEventCursor,
    BotActionEventPage,
    BotActionEventRecord,
    BotActionEventSearchScope,
    BotInstallationRecord,
    BotInstallationRepositoryError,
    DeploymentConfigInput,
    DeploymentConfigRecord,
    DeploymentConfigRepositoryError,
    EncryptedOAuthTokenPayload,
    FluxerOAuthRefreshCompletion,
    FluxerOAuthRefreshLeaseClaim,
    FluxerOAuthRefreshMutationStatus,
    FluxerOAuthTokenRecord,
    FluxerOAuthTokenRepositoryError,
    GuildCommandPermissionRuleRecord,
    GuildCommandPermissionRuleRepositoryError,
    GuildCommandPermissionRuleTargetType,
    GuildCommandSettingsRecord,
    GuildCommandSettingsRepositoryError,
    GuildDashboardPermissionRuleRecord,
    GuildDashboardPermissionRuleRepositoryError,
    GuildFeatureRepositoryError,
    GuildInviteAttributionStatus,
    GuildInviteSnapshotInput,
    GuildInviteSnapshotRecord,
    GuildInviteSnapshotState,
    GuildInviteSnapshotSyncResult,
    GuildMemberFlowEventRecord,
    GuildMemberFlowEventType,
    GuildMessageActivityRecord,
    GuildOverviewAggregate,
    GuildSecurityPolicyRecord,
    GuildSecurityPolicyRepositoryError,
    GrowthOverviewRepositoryError,
    DashboardPostingOperationRecord,
    DashboardPostingOperationRepositoryError,
    DashboardPostingOperationStatus,
    DashboardPostingOperationWorkerRecord,
    MessageTemplateRecord,
    PostedMessageRecord,
    PostingRepositoryError,
    WebSessionRecord,
    WebSessionRepositoryError,
} from './contracts.js';
export type {
    StructureBackupRecord,
    StructureBackupRetentionPruneRecord,
    StructureBackupSettingsRecord,
    StructureBackupSummaryPageRecord,
    StructureBackupSummaryRecord,
    StructureScheduledDriftFieldSummaryRecord,
    StructureScheduledDriftLiveCountsRecord,
    StructureScheduledDriftSummaryRecord,
    StructureImportActionPageRecord,
    StructureImportActionRecord,
    StructureImportActionAttemptRecord,
    StructureImportApprovalRecord,
    StructureImportExecutionClaimRecord,
    StructureImportExecutionMutationAuthorizationRecord,
    StructureImportExecutionProtocolMismatchRecord,
    StructureImportExecutionRecord,
    StructureImportExecutionPhase,
    StructureImportExecutionStatus,
    StructureImportDecisionPageRecord,
    StructureImportDecisionRecord,
    StructureImportExportRepositoryError,
    StructureImportPreflightRecord,
    StructureImportRunRecord,
    StructureImportRunWithActionsRecord,
    StructureObservedEventStateRecord,
} from './contracts-structure.js';
export {
    deleteBotInstallation,
    findDeploymentConfig,
    listBotActionEventPageByGuildId,
    listBotActionEventsByGuildId,
    listBotInstallationGuildIds,
    listGuildSecurityPoliciesByGuildIds,
    recordBotActionEvent,
    upsertBotInstallation,
    upsertDeploymentConfig,
} from './runtime.js';
export {
    deleteGuildCommandPermissionRule,
    findGuildCommandPermissionRule,
    findGuildDashboardPermissionRule,
    listGuildCommandPermissionRulesByGuildId,
    listGuildDashboardPermissionRulesByGuildIds,
    upsertGuildCommandPermissionRule,
    upsertGuildDashboardPermissionRule,
} from './runtime-access.js';
export {
    claimFluxerOAuthTokenRefreshLease,
    completeFluxerOAuthTokenRefresh,
    createWebSession,
    findActiveWebSessionById,
    findUsableFluxerOAuthTokenSetByUserId,
    invalidateFluxerOAuthTokenSet,
    recordFluxerOAuthTokenRefreshFailure,
    revokeWebSession,
    upsertFluxerOAuthTokenSet,
} from './runtime-auth.js';
export {
    deleteGuildDefconExemption,
    findGuildCommandSettingsByGuildId,
    findGuildSecurityPolicyByGuildId,
    listGuildDefconExemptionCategories,
    upsertGuildCommandPrefix,
    upsertGuildDefconExemption,
    upsertGuildSecurityPolicy,
} from './runtime-settings.js';
export {
    listGuildInviteSnapshots,
    loadGuildOverviewAggregate,
    recordGuildMemberFlowEvent,
    recordGuildMemberJoinWithInviteSnapshots,
    recordGuildMessageActivity,
    syncGuildInviteSnapshots,
} from './runtime-growth-overview.js';
export {
    deleteMessageTemplate,
    findMessageTemplateByName,
    listMessageTemplatesByGuildId,
    recordPostedMessage,
    upsertMessageTemplate,
} from './runtime-posting.js';
export {
    claimNextDashboardPostingOperation,
    completeDashboardPostingOperationSent,
    DASHBOARD_POSTING_PAYLOAD_MAX_BYTES,
    DASHBOARD_POSTING_PAYLOAD_MAX_DEPTH,
    deferDashboardPostingOperationBeforeSend,
    enqueueDashboardPostingOperation,
    failDashboardPostingOperationPermanently,
    isDashboardPostingGuildRunnable,
    listDashboardPostingOperationsByGuild,
    markDashboardPostingOperationSendStarted,
    markDashboardPostingOperationUnknown,
    normalizeDashboardPostingPayload,
    readDashboardPostingOperationForWorker,
    recordDashboardPostingOperationExternalMessage,
} from './runtime-posting-operations.js';
export {
    claimDueStructureBackupSetting,
    claimDueStructureDriftSetting,
    clearStructureBackupSettingLease,
    clearStructureDriftSettingLease,
    createStructureBackup,
    createStructureImportRun,
    deleteStructureBackup,
    findLatestStructureDriftBaselineBackupByGuildId,
    findStructureBackupByGuildId,
    findStructureImportRunByGuildId,
    findStructureImportRunWithActionsByGuildId,
    findStructureObservedEventStateByGuildId,
    findStructureBackupSettingsByGuildId,
    listAllStructureImportActionsByRunId,
    listDueStructureBackupSettings,
    listDueStructureDriftSettings,
    listDueStructureBackupRetentionSettings,
    listStructureBackupSummaryPageByGuildId,
    listStructureBackupSummariesByGuildId,
    listStructureBackupsByGuildId,
    listStructureImportActionsByRunIdPage,
    listStructureImportRunsByGuildId,
    recordStructureImportAction,
    recordStructureImportActionsBatch,
    recordStructureObservedEvent,
    recordStructureScheduledDriftResult,
    pruneExpiredStructureBackupsForGuild,
    renameStructureBackup,
    upsertStructureBackupSettings,
} from './runtime-structure.js';
export {
    approveStructureImportPlan,
    authorizeStructureImportExecutionMutation,
    checkpointStructureImportExecution,
    claimNextStructureImportExecution,
    completeAndCheckpointStructureImportActionAttempt,
    enqueueStructureImportExecution,
    ensureStructureImportRestorePoint,
    finalizeStructureImportExecution,
    findActiveStructureImportExecution,
    findLatestStructureImportApproval,
    findLatestStructureImportExecution,
    findLatestStructureImportPreflight,
    prepareStructureImportActionAttempt,
    recordStructureImportPreflight,
    recordStructureImportDecisionsBatch,
    listStructureImportDecisionsPage,
    renewStructureImportExecutionLease,
    requestStructureImportExecutionControl,
    startStructureImportActionAttempt,
    transitionStructureImportPlanState,
} from './runtime-structure-execution.js';
export type { StructureAuditInput } from './runtime-structure-execution.js';
export {
    assertConvexRuntimeContract,
    ConvexRuntimeContractError,
    STRUCTURE_EXECUTION_PROTOCOL_VERSION,
} from './runtime-contract.js';
export { createRuntimeDb, isConvexRuntimeDb, readConvexServiceRuntimeConfig } from './service.js';
export type { RuntimeDbClient } from './service.js';
