import type { LevelingMapping, MilestonesKind } from '@neonflux/backend/contracts'
import { ConfigForm } from './configuration-form'
import type { ConfigSectionProps } from './configuration-form'
import { ChoiceField, NumberField, TemplatePicker } from './configuration-fields'
import { idValue, idsValue, numberValue, templateValue } from './configuration-values'
import { FormInputError } from './settings-form'
import { SearchPicker } from './search-picker'
import { postChannels, publicationChannels, selectableRoles } from './catalog-options'

export function LevelingSettings(props: ConfigSectionProps<'leveling'>) {
  const { data,configRevision: revision,jobs } = props.remote, { settings } = data, common = { queue: props.queue,connected: props.connected,jobs }, picks = { loading: props.catalogLoading,allowManual: props.catalogError,catalog: true }
  return <div className="role-section">
    <ConfigForm<'leveling'> {...common} title="Leveling" description="Configure message XP, cooldown and exclusions. This does not change existing member scores" snapshot={{ revision,values: { enabled: settings.enabled,xpPerMessage: String(settings.xpPerMessage),cooldownSeconds: String(settings.cooldownSeconds),excludedChannelIds: JSON.stringify(settings.excludedChannelIds),excludedRoleIds: JSON.stringify(settings.excludedRoleIds) } }} operation={values => ({ type: 'settings',expectedRevision: settings.revision,patch: { enabled: Boolean(values.enabled),xpPerMessage: numberValue(values.xpPerMessage,1,100,'XP per message'),cooldownSeconds: numberValue(values.cooldownSeconds,15,3600,'XP cooldown seconds'),excludedChannelIds: idsValue(values.excludedChannelIds,50,'excluded XP channels'),excludedRoleIds: idsValue(values.excludedRoleIds,50,'excluded XP roles') } })} fields={(values,edit,disabled) => <><label><input type="checkbox" checked={Boolean(values.enabled)} disabled={disabled} onChange={event => edit('enabled',event.target.checked)} />Leveling enabled</label><NumberField label="XP per message" value={String(values.xpPerMessage)} onChange={value => edit('xpPerMessage',value)} disabled={disabled} min={1} max={100} /><NumberField label="XP cooldown (seconds)" value={String(values.cooldownSeconds)} onChange={value => edit('cooldownSeconds',value)} disabled={disabled} min={15} max={3600} /><SearchPicker {...picks} label="Excluded XP channels" options={publicationChannels(props.catalog)} multiple value={JSON.parse(String(values.excludedChannelIds)) as string[]} disabled={disabled} onChange={ids => edit('excludedChannelIds',JSON.stringify(ids))} /><SearchPicker {...picks} label="Excluded XP roles" options={selectableRoles(props.catalog)} multiple value={JSON.parse(String(values.excludedRoleIds)) as string[]} disabled={disabled} onChange={ids => edit('excludedRoleIds',JSON.stringify(ids))} /><p className="field-help">Up to fifty excluded channels and roles</p></>} />
    <ConfigForm<'leveling'> {...common} title="Level reward roles" description="Configure safe roles earned at distinct levels. Mapping changes may withdraw obsolete roles owned by the bot" snapshot={{ revision,values: { mappings: JSON.stringify(settings.mappings) } }} operation={values => {
      const rows = JSON.parse(String(values.mappings)) as Array<{ level: number | string,roleId: string }>
      if (rows.length > 20) throw new FormInputError('Choose up to twenty reward mappings')
      const mappings: LevelingMapping[] = rows.map(row => ({ level: numberValue(String(row.level),1,1000,'reward level'),roleId: idValue(row.roleId,'reward role') }))
      if (new Set(mappings.map(row => row.level)).size !== mappings.length || new Set(mappings.map(row => row.roleId)).size !== mappings.length) throw new FormInputError('Each reward needs a distinct level and role')
      return { type: 'mappings',expectedMappingRevision: settings.mappingRevision,mappings }
    }} fields={(values,edit,disabled) => {
      const rows = JSON.parse(String(values.mappings)) as Array<{ level: number | string,roleId: string }>, change = (next: typeof rows) => edit('mappings',JSON.stringify(next))
      return <>{rows.map((row,index) => <fieldset className="mapping-row" key={index}><legend>Reward {index + 1}</legend><NumberField label={`Reward level ${index + 1}`} value={String(row.level)} onChange={level => change(rows.map((current,i) => i === index ? { ...current,level } : current))} disabled={disabled} min={1} max={1000} /><SearchPicker {...picks} label={`Reward role ${index + 1}`} options={selectableRoles(props.catalog)} value={row.roleId ? [row.roleId] : []} disabled={disabled} onChange={ids => change(rows.map((current,i) => i === index ? { ...current,roleId: ids[0] ?? '' } : current))} /><button type="button" className="secondary" disabled={disabled} onClick={() => change(rows.filter((_,i) => i !== index))}>Remove reward {index + 1}</button></fieldset>)}<button type="button" className="secondary" disabled={disabled || rows.length >= 20} onClick={() => change([...rows,{ level: 1,roleId: '' }])}>Add level reward</button></>
    }} />
  </div>
}
const milestoneLabels = { birthday: 'Birthday',anniversary: 'Join anniversary' }
export function MilestoneSettings(props: ConfigSectionProps<'milestones'>) {
  const { data,configRevision: revision,jobs } = props.remote, common = { queue: props.queue,connected: props.connected,jobs }, templates = { templates: props.templates,loading: props.templatesLoading,error: props.templatesError,loadMore: props.loadTemplatesPage,hasMore: props.templatesHasMore }
  return <div className="role-section">
    <ConfigForm<'milestones'> {...common} title="Milestones" description="Birthday and join-anniversary routes require member consent and enabled publishing" snapshot={{ revision,values: { enabled: data.settings.enabled } }} operation={values => ({ type: 'settings',expectedRevision: data.settings.revision,enabled: Boolean(values.enabled) })} fields={(values,edit,disabled) => <label><input type="checkbox" checked={Boolean(values.enabled)} disabled={disabled} onChange={event => edit('enabled',event.target.checked)} />Milestones enabled</label>} />
    {(['birthday','anniversary'] as MilestonesKind[]).map(kind => {
      const route = data.routes.find(route => route.kind === kind), title = milestoneLabels[kind]
      const missing = props.removedDefinitions?.includes(kind), card = { ...common,connected: common.connected && !missing }
      return <details key={kind}><summary>{title}: {route ? route.enabled ? 'Enabled' : 'Disabled' : 'Not configured'}</summary><div className="role-section">{missing && <p className="notice" role="status">Not in loaded pages. This draft is kept for copying. Load remaining pages to check whether it moved</p>}
        <ConfigForm<'milestones'> {...card} title={`${title} route`} description="Configure a civil clock, destination and the exact saved template revision" snapshot={{ revision,values: { channelId: route?.channelId ?? '',zone: route?.zone ?? 'UTC',time: route?.time ?? '09:00',fold: route?.fold ?? 'reject',source: route ? JSON.stringify({ kind: 'template',...route.template }) : '' } }} operation={values => { const source = templateValue(values.source); return { type: 'configure',kind,expectedRevision: route?.revision ?? 0,channelId: idValue(values.channelId,'milestone channel'),zone: String(values.zone),time: String(values.time),fold: values.fold as 'reject' | 'earlier' | 'later',template: { name: source.name,revision: source.revision } } }} fields={(values,edit,disabled) => <><SearchPicker catalog label={`${title} channel`} options={publicationChannels(props.catalog)} loading={props.catalogLoading} allowManual={props.catalogError} value={values.channelId ? [String(values.channelId)] : []} onChange={ids => edit('channelId',ids[0] ?? '')} disabled={disabled} /><label>{title} timezone<input required maxLength={128} value={String(values.zone)} disabled={disabled} onChange={event => edit('zone',event.target.value)} /></label><label>{title} local time<input required type="time" step={60} value={String(values.time)} disabled={disabled} onChange={event => edit('time',event.target.value)} /></label><ChoiceField label={`${title} repeated local time`} value={String(values.fold)} onChange={value => edit('fold',value)} disabled={disabled} options={[{ value: 'reject',label: 'Reject ambiguous time' },{ value: 'earlier',label: 'Earlier offset' },{ value: 'later',label: 'Later offset' }]} /><TemplatePicker {...templates} label={`${title} template`} value={String(values.source)} onChange={value => edit('source',value)} disabled={disabled} /><p className="field-help">Use a current Owner or Administrator with destination access. Template placeholders: {'{user}, {server}'}{kind === 'anniversary' && ', {years}'}</p></>} />
        {route && <><ConfigForm<'milestones'> {...card} title={`${title} enabled`} description="Enabling starts future delivery eligibility at the new activation time" snapshot={{ revision,values: { enabled: route.enabled } }} operation={values => ({ type: values.enabled ? 'enable' : 'disable',kind,expectedRevision: route.revision })} fields={(values,edit,disabled) => <label><input type="checkbox" checked={Boolean(values.enabled)} disabled={disabled} onChange={event => edit('enabled',event.target.checked)} />{title} route enabled</label>} /><ConfigForm<'milestones'> {...card} title={`Clear ${title.toLowerCase()} route`} description="Remove the configured route. Existing retained delivery outcomes stay with their owning lifecycle" snapshot={{ revision,values: { confirm: false },context: route.revision }} submitLabel="Clear milestone route" operation={() => ({ type: 'clear',kind,expectedRevision: route.revision })} fields={(values,edit,disabled) => <label><input type="checkbox" checked={Boolean(values.confirm)} disabled={disabled} onChange={event => edit('confirm',event.target.checked)} />Confirm milestone route removal</label>} /></>}
      </div></details>
    })}
  </div>
}
export function SuggestionSettings(props: ConfigSectionProps<'suggestions'>) {
  const { data,configRevision: revision,jobs } = props.remote, { settings } = data, common = { queue: props.queue,connected: props.connected,jobs }
  return <div className="role-section">
    <ConfigForm<'suggestions'> {...common} title="Suggestions" description="Configure future suggestion cards. Existing suggestions retain their destination" snapshot={{ revision,values: { enabled: settings.enabled } }} operation={values => ({ type: 'settings',expectedRevision: settings.revision,enabled: Boolean(values.enabled) })} fields={(values,edit,disabled) => <label><input type="checkbox" checked={Boolean(values.enabled)} disabled={disabled} onChange={event => edit('enabled',event.target.checked)} />Suggestions enabled</label>} />
    <ConfigForm<'suggestions'> {...common} title="Suggestion destination" description="Choose the channel. In a forum or media channel each suggestion becomes its own post with a status tag, and NeonFlux adds the tags it needs. A current Owner or Administrator with destination access confirms it" snapshot={{ revision,values: { channelId: settings.channelId ?? '',ownerId: props.defaultOwnerId ?? '' } }} operation={values => ({ type: 'configure',expectedRevision: settings.revision,channelId: idValue(values.channelId,'suggestion channel'),ownerId: idValue(values.ownerId,'suggestion owner ID') })} fields={(values,edit,disabled) => <><SearchPicker catalog label="Suggestion channel" options={postChannels(props.catalog)} loading={props.catalogLoading} allowManual={props.catalogError} value={values.channelId ? [String(values.channelId)] : []} onChange={ids => edit('channelId',ids[0] ?? '')} disabled={disabled} /><label>Confirming administrator ID<input required inputMode="numeric" maxLength={19} value={String(values.ownerId)} disabled={disabled} onChange={event => edit('ownerId',event.target.value)} /></label></>} />
  </div>
}
