import type { PublishingKind } from '@neonflux/contracts/publishing-base'
import { ConfigForm, ConfigurationPages } from './configuration-form'
import type { ConfigSectionProps } from './configuration-form'
import { ChoiceField } from './configuration-fields'
import { nameValue } from './configuration-values'
import { MessageBuilder } from './message-builder'
import { validateMessage } from './message-content'

const kindChoices = [{ value: 'draft',label: 'Draft' },{ value: 'template',label: 'Template' }]
export function PublishingSettings(props: ConfigSectionProps<'publishing'>) {
  const { data,configRevision: revision,jobs } = props.remote, common = { queue: props.queue,connected: props.connected,jobs }
  return <div className="role-section">
    <ConfigForm<'publishing'> {...common} title="Publishing" description="Publishing controls messages and template consumers such as greetings, events and schedules" snapshot={{ revision,values: { enabled: data.settings.enabled } }} operation={values => ({ type: 'settings',patch: { enabled: Boolean(values.enabled) } })} fields={(values,edit,disabled) => <label><input type="checkbox" checked={Boolean(values.enabled)} disabled={disabled} onChange={event => edit('enabled',event.target.checked)} />Publishing enabled</label>} />
    {data.drafts.map(draft => { const missing = props.removedDefinitions?.includes(`${draft.kind}:${draft.name}`), card = { ...common,connected: common.connected && !missing }; return <details key={`${draft.kind}:${draft.name}`}><summary>{draft.name}: {draft.kind === 'draft' ? 'Draft' : 'Template'}, version {draft.revision}</summary><div className="role-section">{missing && <p className="notice" role="status">Not in loaded pages. This draft is kept for copying. Load remaining pages to check whether it moved</p>}
      <ConfigForm<'publishing'> {...card} title={`${draft.kind === 'draft' ? 'Draft' : 'Template'}: ${draft.name}`} description="Edit all text and embed properties using the shared message builder. Saving creates a new version" snapshot={{ revision,values: { content: JSON.stringify(draft.content) } }} operation={values => ({ type: 'draft-set',kind: draft.kind,name: draft.name,expectedRevision: draft.revision,content: validateMessage(JSON.parse(String(values.content)),false) })} fields={(values,edit,disabled) => <MessageBuilder value={String(values.content)} disabled={disabled} onChange={content => edit('content',content)} />} />
      <ConfigForm<'publishing'> {...card} title={`Clone: ${draft.name}`} description="Copy this saved version to a new draft or template" snapshot={{ revision,values: { kind: draft.kind,name: '' },context: draft.revision }} submitLabel="Copy saved version" operation={values => ({ type: 'draft-clone',kind: draft.kind,name: draft.name,expectedRevision: draft.revision,toKind: values.kind as PublishingKind,toName: nameValue(values.name,'clone name') })} fields={(values,edit,disabled) => <><ChoiceField label="Clone kind" value={String(values.kind)} onChange={value => edit('kind',value)} disabled={disabled} options={kindChoices} /><label>Clone name<input required maxLength={32} value={String(values.name)} disabled={disabled} onChange={event => edit('name',event.target.value)} /></label></>} />
      <ConfigForm<'publishing'> {...card} title={`Delete ${draft.kind}: ${draft.name}`} description="Delete this saved definition. Existing copied template consumers retain their own snapshots" snapshot={{ revision,values: { confirm: false },context: draft.revision }} submitLabel="Delete saved definition" operation={() => ({ type: 'draft-delete',kind: draft.kind,name: draft.name,expectedRevision: draft.revision })} fields={(values,edit,disabled) => <label><input type="checkbox" checked={Boolean(values.confirm)} disabled={disabled} onChange={event => edit('confirm',event.target.checked)} />Confirm saved definition deletion</label>} />
    </div></details> })}
    <ConfigForm<'publishing'> {...common} title="Create draft or template" description="Create a named message definition for publishing or another configured module" snapshot={{ revision,values: { name: '',kind: 'draft',content: JSON.stringify({ content: '' }) } }} submitLabel="Create saved definition" operation={values => ({ type: 'draft-create',kind: values.kind as PublishingKind,name: nameValue(values.name,'draft or template name'),content: validateMessage(JSON.parse(String(values.content)),false) })} fields={(values,edit,disabled) => <><label>Saved definition name<input required maxLength={32} value={String(values.name)} disabled={disabled} onChange={event => edit('name',event.target.value)} /></label><ChoiceField label="Saved definition kind" value={String(values.kind)} onChange={value => edit('kind',value)} disabled={disabled} options={kindChoices} /><MessageBuilder value={String(values.content)} disabled={disabled} onChange={content => edit('content',content)} /></>} />
    <ConfigurationPages nextCursors={props.remote.nextCursors} loadPage={props.loadPage} loading={props.loadingPage} />
  </div>
}
