/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSessionRouteImport } from './routes/api.session'
import { Route as AuthFluxerRouteImport } from './routes/auth.fluxer'
import { Route as AuthLogoutRouteImport } from './routes/auth.logout'
import { Route as AuthFluxerCallbackRouteImport } from './routes/auth.fluxer.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionRoute = ApiSessionRouteImport.update({
  id: '/api/session',
  path: '/api/session',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthFluxerRoute = AuthFluxerRouteImport.update({
  id: '/auth/fluxer',
  path: '/auth/fluxer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthFluxerCallbackRoute = AuthFluxerCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthFluxerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/session': typeof ApiSessionRoute
  '/auth/fluxer': typeof AuthFluxerRouteWithChildren
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/fluxer/callback': typeof AuthFluxerCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/session': typeof ApiSessionRoute
  '/auth/fluxer': typeof AuthFluxerRouteWithChildren
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/fluxer/callback': typeof AuthFluxerCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/session': typeof ApiSessionRoute
  '/auth/fluxer': typeof AuthFluxerRouteWithChildren
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/fluxer/callback': typeof AuthFluxerCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/session'
    | '/auth/fluxer'
    | '/auth/logout'
    | '/auth/fluxer/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/session'
    | '/auth/fluxer'
    | '/auth/logout'
    | '/auth/fluxer/callback'
  id:
    | '__root__'
    | '/'
    | '/api/session'
    | '/auth/fluxer'
    | '/auth/logout'
    | '/auth/fluxer/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiSessionRoute: typeof ApiSessionRoute
  AuthFluxerRoute: typeof AuthFluxerRouteWithChildren
  AuthLogoutRoute: typeof AuthLogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session': {
      id: '/api/session'
      path: '/api/session'
      fullPath: '/api/session'
      preLoaderRoute: typeof ApiSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/fluxer': {
      id: '/auth/fluxer'
      path: '/auth/fluxer'
      fullPath: '/auth/fluxer'
      preLoaderRoute: typeof AuthFluxerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/fluxer/callback': {
      id: '/auth/fluxer/callback'
      path: '/callback'
      fullPath: '/auth/fluxer/callback'
      preLoaderRoute: typeof AuthFluxerCallbackRouteImport
      parentRoute: typeof AuthFluxerRoute
    }
  }
}

interface AuthFluxerRouteChildren {
  AuthFluxerCallbackRoute: typeof AuthFluxerCallbackRoute
}

const AuthFluxerRouteChildren: AuthFluxerRouteChildren = {
  AuthFluxerCallbackRoute: AuthFluxerCallbackRoute,
}

const AuthFluxerRouteWithChildren = AuthFluxerRoute._addFileChildren(
  AuthFluxerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiSessionRoute: ApiSessionRoute,
  AuthFluxerRoute: AuthFluxerRouteWithChildren,
  AuthLogoutRoute: AuthLogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
