import type { AutomodRule, ModerationSettings, StaffClass } from '@neonflux/backend/contracts'
import { ConfigForm } from './configuration-form'
import type { ConfigSectionProps } from './configuration-form'
import { ChoiceField, NumberField, StringList } from './configuration-fields'
import { idValue, idsValue, nameValue, numberValue, stringsValue } from './configuration-values'
import type { FormValues } from './settings-form'
import { SearchPicker } from './search-picker'
import { publicationChannels, selectableRoles } from './catalog-options'

const staffScopes: StaffClass[] = ['moderation','cases','automod','security','appeals']
const flags = ['manualModerationEnabled','appealsEnabled'] as const
const flagLabels = { manualModerationEnabled: 'Manual moderation enabled',appealsEnabled: 'Appeals enabled' }
function ruleValues(rule?: AutomodRule): FormValues {
  return { name: rule?.name ?? '',type: rule?.type ?? 'spam',enabled: rule?.enabled ?? true,priority: String(rule?.priority ?? 0),action: rule?.action ?? 'log',threshold: String(rule?.threshold ?? 5),windowSeconds: String(rule?.windowSeconds ?? 10),durationSeconds: String(rule?.durationSeconds ?? 60),patterns: JSON.stringify(rule?.patterns ?? []),domainMode: rule?.domainMode ?? 'block',channelIds: JSON.stringify(rule?.channelIds ?? []),exemptChannelIds: JSON.stringify(rule?.exemptChannelIds ?? []),exemptRoleIds: JSON.stringify(rule?.exemptRoleIds ?? []) }
}
function ruleValue(values: FormValues): AutomodRule {
  return { name: nameValue(values.name,'rule name'),type: values.type as AutomodRule['type'],enabled: Boolean(values.enabled),priority: numberValue(values.priority,-100,100,'priority'),action: values.action as AutomodRule['action'],threshold: numberValue(values.threshold,1,100,'threshold'),windowSeconds: numberValue(values.windowSeconds,1,300,'window seconds'),durationSeconds: numberValue(values.durationSeconds,1,31536000,'timeout seconds'),patterns: stringsValue(values.patterns,20,200,'patterns'),domainMode: values.domainMode as AutomodRule['domainMode'],channelIds: idsValue(values.channelIds,20,'rule channels'),exemptChannelIds: idsValue(values.exemptChannelIds,20,'exempt channels'),exemptRoleIds: idsValue(values.exemptRoleIds,20,'exempt roles') }
}
export function SafetySettings(props: ConfigSectionProps<'moderation'>) {
  const { remote,queue,connected } = props, { data,configRevision: revision,jobs } = remote, { settings,rules,watchlist } = data
  const common = { queue,connected,jobs }, picks = { loading: props.catalogLoading,allowManual: props.catalogError }, channels = publicationChannels(props.catalog), roles = selectableRoles(props.catalog)
  const settingValues: FormValues = { manualModerationEnabled: settings.manualModerationEnabled,appealsEnabled: settings.appealsEnabled,logChannelId: settings.logChannelId ?? '',...Object.fromEntries(staffScopes.map(scope => [`staff:${scope}`,JSON.stringify(settings.staffRoleIds[scope])])) }
  return <div className="role-section">
    <ConfigForm<'moderation'> {...common} title="Moderation and staff" description="Configure moderation, appeals, staff roles and the existing moderation log destination" snapshot={{ revision,values: settingValues }} operation={values => ({ type: 'settings',patch: { manualModerationEnabled: Boolean(values.manualModerationEnabled),appealsEnabled: Boolean(values.appealsEnabled),logChannelId: values.logChannelId ? idValue(values.logChannelId,'moderation log channel') : null,staffRoleIds: Object.fromEntries(staffScopes.map(scope => [scope,idsValue(values[`staff:${scope}`],20,`${scope} staff roles`)])) as ModerationSettings['staffRoleIds'] } })} fields={(values,edit,disabled) => <>
      {flags.map(key => <label key={key}><input type="checkbox" checked={Boolean(values[key])} disabled={disabled} onChange={event => edit(key,event.target.checked)} />{flagLabels[key]}</label>)}
      <SearchPicker {...picks} label="Moderation log channel" options={channels} value={values.logChannelId ? [String(values.logChannelId)] : []} disabled={disabled} onChange={ids => edit('logChannelId',ids[0] ?? '')} />
      {staffScopes.map(scope => <SearchPicker {...picks} key={scope} label={`${scope[0]!.toUpperCase()}${scope.slice(1)} staff roles`} options={roles} value={JSON.parse(String(values[`staff:${scope}`])) as string[]} multiple disabled={disabled} onChange={ids => edit(`staff:${scope}`,JSON.stringify(ids))} />)}
    </>} />
    <ConfigForm<'moderation'> {...common} title="Automod policy" description="Choose dry-run or enforcement before configuring rules" snapshot={{ revision,values: { enabled: settings.automodEnabled,mode: settings.automodMode } }} operation={values => ({ type: 'settings',patch: { automodEnabled: Boolean(values.enabled),automodMode: values.mode as 'dry-run' | 'enforce' } })} fields={(values,edit,disabled) => <><label><input type="checkbox" checked={Boolean(values.enabled)} disabled={disabled} onChange={event => edit('enabled',event.target.checked)} />Automod enabled</label><ChoiceField label="Automod mode" value={String(values.mode)} onChange={value => edit('mode',value)} disabled={disabled} options={[{ value: 'dry-run',label: 'Dry run' },{ value: 'enforce',label: 'Enforce' }]} /></>} />
    <ConfigForm<'moderation'> {...common} title="Security policy" description="Configure join bursts, honeypots and the user watchlist" snapshot={{ revision,values: { enabled: settings.securityEnabled,mode: settings.securityMode,joinEnabled: settings.joinEnabled,joinThreshold: String(settings.joinThreshold),joinWindowSeconds: String(settings.joinWindowSeconds),joinDefcon2: settings.joinDefcon2,honeypotEnabled: settings.honeypotEnabled,honeypotChannelIds: JSON.stringify(settings.honeypotChannelIds),watchlistEnabled: settings.watchlistEnabled } }} operation={values => ({ type: 'settings',patch: { securityEnabled: Boolean(values.enabled),securityMode: values.mode as 'dry-run' | 'enforce',joinEnabled: Boolean(values.joinEnabled),joinThreshold: numberValue(values.joinThreshold,2,100,'join threshold'),joinWindowSeconds: numberValue(values.joinWindowSeconds,1,300,'join window'),joinDefcon2: Boolean(values.joinDefcon2),honeypotEnabled: Boolean(values.honeypotEnabled),honeypotChannelIds: idsValue(values.honeypotChannelIds,20,'honeypot channels'),watchlistEnabled: Boolean(values.watchlistEnabled) } })} fields={(values,edit,disabled) => <>
      {[['enabled','Security enabled'],['joinEnabled','Join burst detection enabled'],['joinDefcon2','Raise DEFCON to level 2 on a join burst'],['honeypotEnabled','Honeypots enabled'],['watchlistEnabled','Watchlist enabled']].map(([key,label]) => <label key={key}><input type="checkbox" checked={Boolean(values[key!])} disabled={disabled} onChange={event => edit(key!,event.target.checked)} />{label}</label>)}
      <ChoiceField label="Security mode" value={String(values.mode)} onChange={value => edit('mode',value)} disabled={disabled} options={[{ value: 'dry-run',label: 'Dry run' },{ value: 'enforce',label: 'Enforce' }]} />
      <NumberField label="Join burst threshold" value={String(values.joinThreshold)} onChange={value => edit('joinThreshold',value)} disabled={disabled} min={2} max={100} />
      <NumberField label="Join burst window (seconds)" value={String(values.joinWindowSeconds)} onChange={value => edit('joinWindowSeconds',value)} disabled={disabled} min={1} max={300} />
      <SearchPicker {...picks} label="Honeypot channels" options={channels} multiple value={JSON.parse(String(values.honeypotChannelIds)) as string[]} disabled={disabled} onChange={ids => edit('honeypotChannelIds',JSON.stringify(ids))} />
    </>} />
    <ConfigForm<'moderation'> {...common} title="DEFCON" description="Set the effective security level with current Owner or Administrator permission. Level 1 pauses ordinary command and delivery work" snapshot={{ revision,values: { defcon: String(settings.defcon) } }} operation={values => ({ type: 'settings',patch: { defcon: numberValue(values.defcon,1,3,'DEFCON level') as 1 | 2 | 3 } })} fields={(values,edit,disabled) => <ChoiceField label="DEFCON level" value={String(values.defcon)} onChange={value => edit('defcon',value)} disabled={disabled} options={[{ value: '3',label: '3: Normal' },{ value: '2',label: '2: Restricted' },{ value: '1',label: '1: Emergency' }]} />} />
    <section className="panel"><h2>Automod rules</h2><p className="muted">Each rule keeps its type and name. Create a new rule to use a different type</p></section>
    {rules.map(rule => { const missing = props.removedDefinitions?.includes(`rule:${rule.name}`), card = { ...common,connected: common.connected && !missing }; return <details key={rule.name}><summary>{rule.name}: {rule.enabled ? 'Enabled' : 'Disabled'} {rule.type} rule</summary><div className="role-section">{missing && <p className="notice" role="status">Not in loaded pages. This draft is kept for copying. Load remaining pages to check whether it moved</p>}<ConfigForm<'moderation'> {...card} title={`Rule: ${rule.name}`} description="Edit the rule's limits, patterns, action and exemptions" snapshot={{ revision,values: ruleValues(rule) }} operation={values => { const { name,type,...patch } = ruleValue(values); return { type: 'rule-update',name,patch } }} fields={(values,edit,disabled) => <RuleFields values={values} edit={edit} disabled={disabled} existing props={props} />} /><ConfigForm<'moderation'> {...card} title={`Delete rule: ${rule.name}`} description="Remove this rule from future automod evaluation" snapshot={{ revision,values: { confirm: false } }} operation={() => ({ type: 'rule-delete',name: rule.name })} submitLabel="Delete rule" fields={(values,edit,disabled) => <label><input type="checkbox" checked={Boolean(values.confirm)} disabled={disabled} onChange={event => edit('confirm',event.target.checked)} />Confirm rule deletion</label>} /></div></details> })}
    <ConfigForm<'moderation'> {...common} title="Create automod rule" description="Configure a named rule. Native permissions and safety policy still apply before enforcement" snapshot={{ revision,values: ruleValues() }} submitLabel="Create rule" operation={values => ({ type: 'rule-create',rule: ruleValue(values) })} fields={(values,edit,disabled) => <RuleFields values={values} edit={edit} disabled={disabled} props={props} />} />
    {remote.nextCursors?.rules && <button type="button" className="secondary" disabled={props.loadingPage} onClick={() => props.loadPage?.('rules',remote.nextCursors!.rules!)}>Load more rules</button>}
    <section className="panel"><h2>User watchlist</h2><p className="muted">Configuration entries apply to exact user IDs, including users who have not joined</p></section>
    {watchlist.map(entry => { const missing = props.removedDefinitions?.includes(`watchlist:${entry.userId}`), card = { ...common,connected: common.connected && !missing }; return <details key={entry.userId}><summary>User {entry.userId}</summary><div className="role-section">{missing && <p className="notice" role="status">Not in loaded pages. This draft is kept for copying. Load remaining pages to check whether it moved</p>}<ConfigForm<'moderation'> {...card} title={`Watchlist user: ${entry.userId}`} description="Update the configured reason" snapshot={{ revision,values: { reason: entry.reason } }} operation={values => ({ type: 'watchlist-add',userId: entry.userId,reason: String(values.reason) })} fields={(values,edit,disabled) => <label>Watchlist reason<textarea required maxLength={512} value={String(values.reason)} disabled={disabled} onChange={event => edit('reason',event.target.value)} /></label>} /><ConfigForm<'moderation'> {...card} title={`Remove watchlist user: ${entry.userId}`} description="Stop applying this entry to future observations" snapshot={{ revision,values: { confirm: false } }} submitLabel="Remove watchlist entry" operation={() => ({ type: 'watchlist-remove',userId: entry.userId })} fields={(values,edit,disabled) => <label><input type="checkbox" checked={Boolean(values.confirm)} disabled={disabled} onChange={event => edit('confirm',event.target.checked)} />Confirm watchlist removal</label>} /></div></details> })}
    <ConfigForm<'moderation'> {...common} title="Add watchlist user" description="Enter an exact user ID and the configuration reason" snapshot={{ revision,values: { userId: '',reason: '' } }} submitLabel="Add watchlist entry" operation={values => ({ type: 'watchlist-add',userId: idValue(values.userId,'watchlist user ID'),reason: String(values.reason) })} fields={(values,edit,disabled) => <><label>Watchlist user ID<input required inputMode="numeric" maxLength={19} value={String(values.userId)} disabled={disabled} onChange={event => edit('userId',event.target.value)} /></label><label>Watchlist reason<textarea required maxLength={512} value={String(values.reason)} disabled={disabled} onChange={event => edit('reason',event.target.value)} /></label></>} />
    {remote.nextCursors?.watchlist && <button type="button" className="secondary" disabled={props.loadingPage} onClick={() => props.loadPage?.('watchlist',remote.nextCursors!.watchlist!)}>Load more watchlist users</button>}
  </div>
}
function RuleFields({ values,edit,disabled,existing,props }: { values: FormValues,edit: (key: string,value: string | boolean) => void,disabled: boolean,existing?: boolean,props: ConfigSectionProps<'moderation'> }) {
  const picks = { loading: props.catalogLoading,allowManual: props.catalogError }, channels = publicationChannels(props.catalog), roles = selectableRoles(props.catalog)
  return <>
    {!existing && <><label>Rule name<input required maxLength={32} value={String(values.name)} disabled={disabled} onChange={event => edit('name',event.target.value)} /></label><ChoiceField label="Rule type" value={String(values.type)} onChange={value => edit('type',value)} disabled={disabled} options={['spam','repeat','mentions','words','domains','invites'].map(value => ({ value,label: value[0]!.toUpperCase() + value.slice(1) }))} /></>}
    <label><input type="checkbox" checked={Boolean(values.enabled)} disabled={disabled} onChange={event => edit('enabled',event.target.checked)} />Rule enabled</label>
    <ChoiceField label="Rule action" value={String(values.action)} onChange={value => edit('action',value)} disabled={disabled} options={['log','delete','warn','timeout'].map(value => ({ value,label: value[0]!.toUpperCase() + value.slice(1) }))} />
    <NumberField label="Rule priority" value={String(values.priority)} onChange={value => edit('priority',value)} disabled={disabled} min={-100} max={100} />
    <NumberField label="Rule threshold" value={String(values.threshold)} onChange={value => edit('threshold',value)} disabled={disabled} min={1} max={100} />
    <NumberField label="Rule window (seconds)" value={String(values.windowSeconds)} onChange={value => edit('windowSeconds',value)} disabled={disabled} min={1} max={300} />
    <NumberField label="Rule timeout (seconds)" value={String(values.durationSeconds)} onChange={value => edit('durationSeconds',value)} disabled={disabled} min={1} max={31536000} />
    <StringList label="Rule patterns" value={String(values.patterns)} onChange={value => edit('patterns',value)} disabled={disabled} max={20} maxLength={200} />
    <ChoiceField label="Domain match mode" value={String(values.domainMode)} onChange={value => edit('domainMode',value)} disabled={disabled} options={[{ value: 'block',label: 'Block listed domains' },{ value: 'allow',label: 'Allow listed domains' }]} />
    <SearchPicker {...picks} label="Rule channels" options={channels} multiple value={JSON.parse(String(values.channelIds)) as string[]} disabled={disabled} onChange={ids => edit('channelIds',JSON.stringify(ids))} />
    <SearchPicker {...picks} label="Exempt channels" options={channels} multiple value={JSON.parse(String(values.exemptChannelIds)) as string[]} disabled={disabled} onChange={ids => edit('exemptChannelIds',JSON.stringify(ids))} />
    <SearchPicker {...picks} label="Exempt roles" options={roles} multiple value={JSON.parse(String(values.exemptRoleIds)) as string[]} disabled={disabled} onChange={ids => edit('exemptRoleIds',JSON.stringify(ids))} />
  </>
}
