import { v } from 'convex/values';

import type { Doc } from '../_generated/dataModel.js';

const nullableString = v.union(v.string(), v.null());

export const planMetadataRecordValidator = v.object({
    authorityDigest: v.string(),
    authorityVersion: v.literal(1),
    blockerCount: v.number(),
    createdAt: v.string(),
    createdByUserId: nullableString,
    decisionCount: v.number(),
    decisionLedgerDigest: v.string(),
    decisionSummary: v.object({
        noOp: v.number(),
        create: v.number(),
        update: v.number(),
        delete: v.number(),
        protectedRetained: v.number(),
        protectedOmitted: v.number(),
        unmanagedRetained: v.number(),
        blockedAmbiguous: v.number(),
        blockedUnsupported: v.number(),
    }),
    deleteSetDigest: nullableString,
    deleteStepCount: v.number(),
    executionAuthorityDigest: v.string(),
    executionAuthorityVersion: v.literal(1),
    guildId: v.string(),
    id: v.string(),
    planDigest: v.string(),
    planVersion: v.literal(4),
    policy: v.union(v.literal('merge'), v.literal('synchronize'), v.literal('rebuild')),
    projectedSnapshotDigest: v.string(),
    requestedSnapshotDigest: v.string(),
    sealedAt: v.union(v.string(), v.null()),
    sourceBackupId: nullableString,
    status: v.union(
        v.literal('draft'),
        v.literal('needs_input'),
        v.literal('review_ready'),
        v.literal('approved'),
        v.literal('obsolete')
    ),
    stepCount: v.number(),
    stepLedgerDigest: v.string(),
    summary: v.object({
        creates: v.number(),
        updates: v.number(),
        deletes: v.number(),
        roles: v.number(),
        categories: v.number(),
        channels: v.number(),
    }),
    updatedAt: v.string(),
});

export const preflightMetadataRecordValidator = v.object({
    capabilityFingerprint: v.string(),
    checkedAt: v.string(),
    evidenceDigest: v.string(),
    evidenceVersion: v.literal(1),
    expiresAt: v.string(),
    fingerprintVersion: v.literal(2),
    guildId: v.string(),
    id: v.string(),
    observationSource: v.literal('resident-client'),
    observedAt: v.string(),
    planDigest: v.string(),
    planId: v.string(),
    preflightDigest: v.string(),
    status: v.union(v.literal('ready'), v.literal('blocked'), v.literal('stale')),
    structureFingerprint: v.string(),
    summary: v.object({
        destructiveApprovalRequired: v.number(),
        invalidPlan: v.number(),
        mappingRequired: v.number(),
        ready: v.number(),
        stale: v.number(),
        total: v.number(),
        unsupported: v.number(),
    }),
});

export const hotRunRecordValidator = v.object({
    appliedSteps: v.number(),
    authorizationDecision: v.optional(v.string()),
    authorizationMismatchJson: v.optional(v.string()),
    completedMutationSteps: v.number(),
    completedAt: v.optional(v.string()),
    controlRequest: v.optional(v.union(v.literal('pause'), v.literal('cancel'))),
    createdAt: v.string(),
    currentStepDomain: v.optional(v.string()),
    currentStepId: v.optional(v.string()),
    currentStepLabel: v.optional(v.string()),
    errorType: v.optional(v.string()),
    executionAuthorityDigest: v.string(),
    expectedCapabilityFingerprint: v.string(),
    expectedStructureFingerprint: v.string(),
    failedSteps: v.number(),
    fingerprintVersion: v.literal(2),
    guildId: v.string(),
    heartbeatAt: v.optional(v.string()),
    id: v.string(),
    leaseExpiresAt: v.optional(v.string()),
    leaseId: v.optional(v.string()),
    leaseOwner: v.optional(v.string()),
    mutationAuthorizationLeaseId: v.optional(v.string()),
    mutationAuthorizedAt: v.optional(v.string()),
    nextStepSequence: v.number(),
    notStartedSteps: v.number(),
    phase: v.string(),
    planId: v.string(),
    preflightId: v.string(),
    preflightDigest: v.string(),
    preflightExpiresAt: v.string(),
    protocolVersion: v.number(),
    restorePointBackupId: v.optional(v.string()),
    restorePointSnapshotDigest: v.optional(v.string()),
    retryAt: v.optional(v.string()),
    skippedSteps: v.number(),
    startedAt: v.optional(v.string()),
    status: v.string(),
    totalMutationSteps: v.number(),
    totalSteps: v.number(),
    updatedAt: v.string(),
    terminalDigest: v.optional(v.string()),
    terminalRequestDigest: v.optional(v.string()),
    verificationEvidenceDigest: v.optional(v.string()),
    verificationEvidenceVersion: v.optional(v.literal(1)),
    verificationStatus: v.optional(v.union(v.literal('matched'), v.literal('mismatch'), v.literal('read_failed'))),
});

export function toPlanMetadataRecord(plan: Omit<Doc<'blueprintPlans'>, '_creationTime'>) {
    return {
        authorityDigest: plan.authorityDigest,
        authorityVersion: plan.authorityVersion,
        blockerCount: plan.blockerCount,
        createdAt: plan.createdAt,
        createdByUserId: plan.createdByUserId ?? null,
        decisionCount: plan.decisionCount,
        decisionLedgerDigest: plan.decisionLedgerDigest,
        decisionSummary: plan.decisionSummary,
        deleteSetDigest: plan.deleteSetDigest ?? null,
        deleteStepCount: plan.deleteStepCount,
        executionAuthorityDigest: plan.executionAuthorityDigest,
        executionAuthorityVersion: plan.executionAuthorityVersion,
        guildId: plan.guildId,
        id: String(plan._id),
        planDigest: plan.planDigest,
        planVersion: plan.planVersion,
        policy: plan.policy,
        projectedSnapshotDigest: plan.projectedSnapshotDigest,
        requestedSnapshotDigest: plan.requestedSnapshotDigest,
        sealedAt: plan.sealedAt ?? null,
        sourceBackupId: plan.sourceBackupId ? String(plan.sourceBackupId) : null,
        status: plan.status,
        stepCount: plan.stepCount,
        stepLedgerDigest: plan.stepLedgerDigest,
        summary: plan.summary,
        updatedAt: plan.updatedAt,
    };
}

export function toPreflightMetadataRecord(preflight: Omit<Doc<'blueprintPlanPreflights'>, '_creationTime'>) {
    return {
        capabilityFingerprint: preflight.capabilityFingerprint,
        checkedAt: preflight.checkedAt,
        evidenceDigest: preflight.evidenceDigest,
        evidenceVersion: preflight.evidenceVersion,
        expiresAt: preflight.expiresAt,
        fingerprintVersion: preflight.fingerprintVersion,
        guildId: preflight.guildId,
        id: String(preflight._id),
        observationSource: preflight.observationSource,
        observedAt: preflight.observedAt,
        planDigest: preflight.planDigest,
        planId: String(preflight.planId),
        preflightDigest: preflight.preflightDigest,
        status: preflight.status,
        structureFingerprint: preflight.structureFingerprint,
        summary: preflight.summary,
    };
}

export function toHotRunRecord(run: Omit<Doc<'blueprintRuns'>, '_creationTime'>) {
    return {
        appliedSteps: run.appliedSteps,
        ...(run.authorizationDecision === undefined ? {} : { authorizationDecision: run.authorizationDecision }),
        ...(run.authorizationMismatchJson === undefined
            ? {}
            : { authorizationMismatchJson: run.authorizationMismatchJson }),
        completedMutationSteps: run.completedMutationSteps,
        ...(run.completedAt === undefined ? {} : { completedAt: run.completedAt }),
        ...(run.controlRequest === undefined ? {} : { controlRequest: run.controlRequest }),
        createdAt: run.createdAt,
        ...(run.currentStepDomain === undefined ? {} : { currentStepDomain: run.currentStepDomain }),
        ...(run.currentStepId === undefined ? {} : { currentStepId: run.currentStepId }),
        ...(run.currentStepLabel === undefined ? {} : { currentStepLabel: run.currentStepLabel }),
        ...(run.errorType === undefined ? {} : { errorType: run.errorType }),
        executionAuthorityDigest: run.executionAuthorityDigest,
        expectedCapabilityFingerprint: run.expectedCapabilityFingerprint,
        expectedStructureFingerprint: run.expectedStructureFingerprint,
        failedSteps: run.failedSteps,
        fingerprintVersion: run.fingerprintVersion,
        guildId: run.guildId,
        ...(run.heartbeatAt === undefined ? {} : { heartbeatAt: run.heartbeatAt }),
        id: String(run._id),
        ...(run.leaseExpiresAt === undefined ? {} : { leaseExpiresAt: run.leaseExpiresAt }),
        ...(run.leaseId === undefined ? {} : { leaseId: run.leaseId }),
        ...(run.leaseOwner === undefined ? {} : { leaseOwner: run.leaseOwner }),
        ...(run.mutationAuthorizationLeaseId === undefined
            ? {}
            : { mutationAuthorizationLeaseId: run.mutationAuthorizationLeaseId }),
        ...(run.mutationAuthorizedAt === undefined ? {} : { mutationAuthorizedAt: run.mutationAuthorizedAt }),
        nextStepSequence: run.nextStepSequence,
        notStartedSteps: run.notStartedSteps,
        phase: run.phase,
        planId: String(run.planId),
        preflightDigest: run.preflightDigest,
        preflightExpiresAt: run.preflightExpiresAt,
        preflightId: String(run.preflightId),
        protocolVersion: run.protocolVersion,
        ...(run.restorePointBackupId === undefined ? {} : { restorePointBackupId: run.restorePointBackupId }),
        ...(run.restorePointSnapshotDigest === undefined
            ? {}
            : { restorePointSnapshotDigest: run.restorePointSnapshotDigest }),
        ...(run.retryAt === undefined ? {} : { retryAt: run.retryAt }),
        skippedSteps: run.skippedSteps,
        ...(run.startedAt === undefined ? {} : { startedAt: run.startedAt }),
        status: run.status,
        ...(run.terminalDigest === undefined ? {} : { terminalDigest: run.terminalDigest }),
        ...(run.terminalRequestDigest === undefined ? {} : { terminalRequestDigest: run.terminalRequestDigest }),
        totalMutationSteps: run.totalMutationSteps,
        totalSteps: run.totalSteps,
        updatedAt: run.updatedAt,
        ...(run.verificationEvidenceDigest === undefined
            ? {}
            : { verificationEvidenceDigest: run.verificationEvidenceDigest }),
        ...(run.verificationEvidenceVersion === undefined
            ? {}
            : { verificationEvidenceVersion: run.verificationEvidenceVersion }),
        ...(run.verificationStatus === undefined ? {} : { verificationStatus: run.verificationStatus }),
    };
}
